### ISSUE TITLE
Feeding text into Discourse Network Analyzer and creating database ( .dna file)

### ISSUE THREAD

**Issue by mjboulle** [leifeld/dna#101]
Is it possible to feed text data, such as a word document with multiple news article straight into Discourse Network Analyzer? It only seems possible when a database has been created, and then new articles can be added by copying and pasting. But then how does one develop the initial database that is required (the .dna file)?

**Comment by leifeld** [comment]
There is a text file import function in the Documents menu. To use this function, you will need each document to be in a separate text file. Just the text of the document. The meta-data, such as title, date, author etc. can be parsed from the file name using regular expressions.

**Comment by StefanLindow** [comment]
tried to do so, but on the one hand I do not understand the import function, e.g. how I may import author, title, date etc. (through a certain way of naming it?), on the other: plain text txt (exported from pdf) looked good in my text editor but mutated vowels (Umlaute) and special characters are replaced by question-mark-signs. 
 
(MacOS 10.11.6, Adobe Acrobat 8.1.0., TextEdit 1.11, dna 2.0 beta 19)
--

**Comment by leifeld** [comment]
You can name the files in arbitrary ways as long as your naming convention is consistent across documents. You can then use regular expressions to parse the relevant fields from the file name. See here, for example: http://www.regular-expressions.info/

About the special characters: did you try saving the text files in UTF-8 Unicode encoding?

**Comment by leifeld** [comment]
Also take a look at this description:
[III. Importing and Organizing your Raw Data.pdf](https://github.com/leifeld/dna/files/1299817/III.Importing.and.Organizing.your.Raw.Data.pdf)
This is a preliminary tutorial part that I haven't reviewed yet. So I can neither answer questions nor guarantee that it is correct; but perhaps it will be helpful.

**Comment by StefanLindow** [comment]
Thanks Philip, works perfect, learning some computer language on the side = nice, too. The tutorial is very thorough and I am looking forward for the whole description
