### ISSUE TITLE
Import errors dna2 to dna2

### ISSUE THREAD

**Issue by StefanLindow** [leifeld/dna#102]
I started coding with a database consisting of multiple different concept-items to choose from, but realized that I should stick to your one concept-item (and do distinctions within there). So I had to start over with a new database with differing (lower) numbers of statements items (but same number of variables). As I try to import the old database into the new one two interrelated problems occur:

1) the import window freezes at "(4/5) saving statements to database"
2) When pressing abort (the only option), newly added texts appear coded (coloured in the coders' colour) as in the original, the statement list on the right shows the coded text snippets with numbers, but no coding window opens when clicking the coded part (neither in the statement list nor in the text itself). 

This is due to the differing statement types Of course, a function (and menu) to choose how to collapse certain statement types into one would be nice. But having the statements colored with just the need to give them new values, that's allright. Nonetheless, it seems (but is not 100% unclear to me) that the all statements of the original database are now imported and marked. (-- adding: in only a few import cases I may compare number of statements, of course.)

Adding another problem: Since the statements are in my statement list, but may not be opened as such by clicking on them, I can not change or delete them if I want to. So even if I find the my original statements now easily, I have to add new statements to add values. Thus a kind of "ghost" statements remains, unclear how they will effect the later data export.

**Comment by leifeld** [comment]
It could be that the import function currently only works properly for the default variables, not for custom statement types. I will need to work on this at some point, but I'm currently packed with work...

**Comment by leifeld** [comment]
Fixed in version 3.0, which will be released later this year. Won't update version 2.0.
