### ISSUE TITLE
Export Articles back to CSV

### ISSUE THREAD

**Issue by cgnguyen** [leifeld/dna#105]
Is there an easy way to export the diffderent artciles back into a single CSV file so I can use it in a different program?  

Just to give an example of my current use case: I want to assign roughly equal length articles to each of the coders, so having the ability to quickly gather summary statistics on each article would help a lot. I don't think that function needs to be added to the program itself, but an export to CSV would be really useful for this.

**Comment by leifeld** [comment]
@JBGruber: please add functionality to rDNA for extracting and adding documents and their meta-data.

**Comment by leifeld** [comment]
We have recently added a function `dna_getDocuments` to the `rDNA` package. This allows you to retrieve all documents as a `data.frame` in `R`. You can then save it to a CSV file using `write.csv`. Would this help?

**Comment by leifeld** [comment]
Closing this issue as there is no further reply.
