### ISSUE TITLE
sample.dna duplicate file in code base

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#106]
Check why there are two `sample.dna` files in the code base. Are they identical? If so, delete one of them.

**Comment by JBGruber** [comment]
Files were identical except time stamp of last use.

**Comment by leifeld** [comment]
Just realized that the `sample.dna` file in the `manual` folder was necessary for the compilation of the `Rnw` document. Perhaps revert that last change then? Thanks.

**Comment by JBGruber** [comment]
I just realised that we could replace `sample.dna` with the new function `dna_sample()` (13af7804491d4aa50b7b6cc08a9383ab9d3d8a0e) in the manual. This would make the second `sample.dna` file obsolete.
