### ISSUE TITLE
Issues in the manual

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#111]
1) Some error message in the "hello world" code block on page 10 in the manual.

2) A compilation warning about multiply defined labels.

**Comment by leifeld** [comment]
There are also some other issues. Screenshot attached. 

![screenshot_2018-02-23_16-44-15](https://user-images.githubusercontent.com/5451293/36605557-f637466c-18b8-11e8-8bac-a1aedb08f216.png)

**Comment by JBGruber** [comment]
1. Seems I replaced too many "*" with \cdot in commit 24594712045ac206ec09bf84e88971a228959cba. There were also new warning messages that sneaked in with the latest rDNA update. Undone in 4880b13e63e58cd5fb622e019d4d25c8d1029329.

2. The label "tab:permissions" is only defined once. This is a problem with the tabularx in section 4.2 User management. We already discussed that but your suggested fix of putting a table environment around it did not do the trick, unfortunately (it created even more trouble). I look into it again next week. Might be worth doing this with kableExtra instead (like tables in chapter 7) to make tables look more alike.

3. I uploaded the missing png. I checked the over/underfull boxes already and took care of the ones you can see with your bare eye. There might be some new ones now, so I'll check again. "Incompatible color" is a knitr issue (See https://github.com/yihui/knitr/issues/1068) I tried the suggested fix, which does not seem to work anymore. I would suggest we ignore the warnings as the problem does not seem to have any effect.

**Comment by JBGruber** [comment]
I just realised what my mistake was when using the fix from the link above. Xcolor issues are gone with commit dae5567e364d16933a03be9ff19b9927a1f0d82a.
