### ISSUE TITLE
Format bibliography in dna-manual.bib

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#112]
1. Format all citation keys as in `leifeld2018temporal` (last name of first author, year, first significant title word).
2. Sort citations in bib file alphabetically by first author, then year, then title.
3. Format all references in title style, including capitalisation of the first word after a colon.
4. Ensure there is exactly one blank line between citations.
5. Ensure all authors are included in the author field as last name, first name (e.g., `Butts, Carter T.`).
6. Do not cite conference papers or other non-published content like working papers (exception: R packages).
7. Remove comments from .bib file.
8. Remove abstracts and other non-relevant fields.
9. Ensure there is no weird formatting (e.g., no line breaks within titles etc.).

**Comment by JBGruber** [comment]
1. Done.

2. Done.

3. Can you elaborate? What else do you want to capitalise? What do you mean by title style?

4. Done. 

5. Done.

6. Done. This removes several topics from the mass citation in the intro though.

7. Done

8. Abstracts removed. What else do you consider non-relevant fields? Keywords and (physical) addresses are probably useless. I would keep as much as possible though in case we want to switch to a different style which e.g., includes DOIs and URLs

9. Done.

**Comment by JBGruber** [comment]
Ok, this should be done. I used R to format title style (see [toTitleCase](https://stat.ethz.ch/R-manual/R-devel/library/tools/html/toTitleCase.html)) and also to compare fields. I also lowercased field names while on it.

Removed fields:
"issn", "urldate", "keywords"

I excluded DOI, URL **and ISBN** from removal even though they were not mentioned in your link.

**Comment by leifeld** [comment]
Can you go through the entries again and fix some entries manually where it didn't work properly? E.g., Imbert; Haunss et al.; Herweg; Csardi et al.; Goodreau et al. and a few others? Also remove working papers and tech reports where necessary. E.g., Herweg.

**Comment by leifeld** [comment]
I think there was a misunderstanding. Title style does not entail wrapping all capital letters in curly braces. It just means using capital letters for significant words. The bibliography style will then determine whether the capitalised words are still capitalised or not. Some styles do this while others don't. It's still important to have this right in the bib file so we can later decide what kind of style to use. Only names, geographical locations etc. should be capitalised with the first letter in curly braces.

**Comment by JBGruber** [comment]
This was a misunderstanding then indeed. I thought you wanted to force title style but keep the bibliography style.

The German titles still have first letters capitalised for grammatical correctness.
