### ISSUE TITLE
RStudio 1.1.423

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#117]
The manual suggests downloading 1.1.419 although 1.1.423 is available via gdebi. Why the old version? Also, the problem with libgstream does not seem to occur in my case with 1.1.423.

**Comment by JBGruber** [comment]
Perfect! It was only available as a preview when I last checked. I'll swap it in the manual.

We should check every now and then and replace with the newest versions of:
-R
-RStudio
-Java
-ubuntu
(Just leaving this here as a note)
