### ISSUE TITLE
expand_scale(add = offset)

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#118]
See attached screenshot for an error message that I get when I compile the manual. I have `ggplot2` 2.2.1 and `ggraph` 1.0.1 installed.

![screenshot_2018-03-03_00-07-06](https://user-images.githubusercontent.com/5451293/36926302-4b50f256-1e77-11e8-8fd3-1dd0c23017df.png)

**Comment by JBGruber** [comment]
As it turns out, `expand_scale()` is not available in the CRAN version of `ggplot2`. I removed it completely in commit e3190513e4b81d7bb9a34c496b6968dab5957abf.

I downgraded `ggplot2` and was able to compile the manual without errors.
