### ISSUE TITLE
dna_plotCentrality and integer qualifiers and custom qualifier variable names

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#122]
Does the `dna_plotCentrality` function in `rDNA` work with integer values or only with binary qualifiers? From what I can see in the code, it looks like the "agreement" variable is hard-coded there, but in principle the name of the variable could be different, and we could have integer rather than binary values. Can you confirm and/or fix please, @JBGruber?

**Comment by JBGruber** [comment]
Agreement wasn't hardcoded. That was just a fragment. I renamed the internal variable now.

But taking care of non-binary qualifiers took a bit more effort. This is how a plot with integer qualifiers looks now:
![integer-qualifier](https://user-images.githubusercontent.com/23524101/38504955-f903a458-3c0d-11e8-8d81-eedebb8d9d74.png)

The size of the bar is determined by the size of the qualifier. If you have two statements with agreement = 5 (and nothing else) the bar will be as tall as if there were 10 statements with qualifier 1.
