### ISSUE TITLE
Changes to dna_plotNetwork

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#125]
1. Currently, the `dna_plotNetwork` function accepts networks as generated by `dna_network`, but also connections and cluster objects. I think the function should only accept objects generated by `dna_network` because everything else will be very confusing. Clusters can be specified through some argument, perhaps "groups". More generally, the workflow in `rDNA` should be 1) create network or cluster object, 2) plot it using one of the functions. For networks, use `dna_plotNetwork`; for cluster objects, use `dna_plotDendrogram` and dna_plotMDS`.
2. Improve documentation in Rd file. What are default and recommended values for `node_size`? What values are accepted for `node_attribute`? What layouts are possible? Enumerate the possibilities here. Etc. Improve help file for `dna_plotNetwork` more generally.
3. The mechanism for assigning node colors is not perfect. The default behaviour should be to plot the colors inherent in the attribute "color". Right now, some weird fix via `identity` and `node_attribute` is required. There are also many arguments. Is it possible to reduce the number of arguments needed for this by overloading the argument with different data types?
4. Is is unclear how groups from a cluster analysis can be plotted other than by handing over the cluster object. That is, does the `groups` argument accept cluster objects? The `groups` argument is not sufficiently documented anyway.

**Comment by JBGruber** [comment]
1. I usually don't like taking features away after they have already been implemented but I can see how this might be confusing. `dna_plotNetwork` and `dna_plotHive` now only take network objects created with `dna_network`.
2. I don't really understand what you mean with recommended values. This depends on the user's settings and plotting environment. The current default (6) is what looks best in .Rnw files (i.e., the manual) and R Notebooks. I overhauled the remaining documentation.
3. I reworked the mechanism for assigning node colours. Nodes are coloured using the color attribute set by the user in DNA. We can discuss reducing the number of arguments but I think it would make things more confusing in most cases I can think of.
4. Cluster object can now be passed using the `groups` argument. I enhanced the documentation and added an example.

Once 2. is solved we can close this.
