### ISSUE TITLE
dna_attributes

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#129]
Can we delete the `dna_attributes` function now that we have `dna_getAttributes`? Or is there any reason we need to keep it?

I think the frequencies can be generated relatively easily by the user by using the `dna_network` function using two-mode networks with separate networks for each level of the qualifier variable and duplicates switched on. Or should we have a separate convenience function that generates frequencies for a selected set of actors and a time period? I would tend to say no.

The actual attributes should not differ between `dna_attributes` and `dna_getAttributes`, I believe. And `dna_getAttributes` also has a `values` argument, so the selection of entries can be restricted to the network the user creates.

I also don't think `dna_attributes` is used in any other function. Correct?

To do:
@JBGruber Answer here if the function can be deleted.
@JBGruber Delete function in `R` code.
@leifeld Delete relevant functions in Java code.

**Comment by JBGruber** [comment]
> Can we delete the dna_attributes function now that we have dna_getAttributes? Or is there any reason we need to keep it?

I went through the code already and swapped all mentions of `dna_attributes` with `dna_getAttributes`. I did not encounter any problems. I compiled the manual as a test and get no errors.

> I think the frequencies can be generated relatively easily by the user by using the dna_network function using two-mode networks with separate networks for each level of the qualifier variable and duplicates switched on.

I'm not sure what this has to do with it.  `dna_getAttributes` still delivers a frequency count but one that is not separated by level of the qualifier as far as I know. What you refer to is done in `dna_cluster` though and the user can get it with `clust <- dna_cluster(conn); clust$network`.

> Or should we have a separate convenience function that generates frequencies for a selected set of actors and a time period? I would tend to say no.

Both options can be set in `dna_cluster` by passing on the arguments to `dna_network` with the `...`. If you think it makes sense, I can add an explanation to the manual.

> The actual attributes should not differ between dna_attributes and dna_getAttributes, I believe. And dna_getAttributes also has a values argument, so the selection of entries can be restricted to the network the user creates.

The only difference I could see was `dna_attributes` delivered two extra columns ("in dataset" and "in network") which I always found very confusing. It think we are better off without that.

> I also don't think dna_attributes is used in any other function. Correct?

Yes

**Comment by leifeld** [comment]
No, the `dna_attributes` function differed from `dna_getAttributes` in that it performed all operations on the filtered set of statements (i.e., after applying a certain time window, filtering out duplicates, removing isolates and so on). Therefore the frequency counts usually differed. But if the user wants this kind of more specialised frequency count to work in conjunction with `dna_network`, they can just create it on their own using `dna_network`. So I'll close this once the respective functions have been removed from the Java code as well.
