### ISSUE TITLE
dna database can not be connected to rDNA

### ISSUE THREAD

**Issue by StefanLindow** [leifeld/dna#134]
Next problem. my dna database can not be connected to rDNA, even though opening it with DNA works just fine.

`>conn2 <- dna_connection("diss-2018-05-10.dna")`

> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: SETTINGS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllSettings(SqlConnection.java:654)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1050)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: DOCUMENTS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllDocuments(SqlConnection.java:400)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1051)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: CODERS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllCoders(SqlConnection.java:1181)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1052)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: CODERRELATIONS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllCoderRelations(SqlConnection.java:487)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1053)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: REGEXES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllRegexes(SqlConnection.java:438)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1054)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTLINKS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllStatementLinks(SqlConnection.java:463)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1055)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTTYPES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllStatementTypes(SqlConnection.java:1142)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1056)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1061)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: ATTRIBUTES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllAttributes(SqlConnection.java:612)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1131)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> Data loaded: 0 statements and 0 documents.
> DNA database: diss-2018-05-10.dna
> 0 statements in 0 documents
> Statement types:

**Comment by JBGruber** [comment]
This error message looks pretty extreme but the important part is actually just `SQL error or missing database`. It tells me that the file "diss-2018-05-10.dna" does not exist in your current working directory. You can switch to the directory where your file is located with `setwd("~/path/to/your/directory")` (or use RStudios Session -> Set Working Directory) or you can use an absolute part to your file: 
```
conn <- dna_connection("/path/to/your/file/diss-2018-05-10.dna")`
```
This should hopefully solve your problem.

I will write a more comprehensive error message because the Java output above does indeed look pretty confusing.

**Comment by leifeld** [comment]
The other possibility is that this is an old file version (pre-2.0). To me, it sounds like the file exists but is not an SQLite database or there are no tables inside. The 1.31 version of DNA used XML instead of a database, so that would make sense. You can download a program called SQLite Browser and open your file. If you same some tables there, this could be a DNA-related problem. If that program also complains and tells you this is not an SQLite database, then the file must be corrupt.

**Comment by StefanLindow** [comment]
I think I started the file with 2.0. I just created a new test file with the newest release and it does the same.
[test.dna.zip](https://github.com/leifeld/dna/files/1994637/test.dna.zip)

` > conntest <- dna_connection("test.dna")'

> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: SETTINGS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllSettings(SqlConnection.java:654)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1050)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: DOCUMENTS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllDocuments(SqlConnection.java:400)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1051)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: CODERS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllCoders(SqlConnection.java:1181)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1052)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: CODERRELATIONS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllCoderRelations(SqlConnection.java:487)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1053)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: REGEXES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllRegexes(SqlConnection.java:438)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1054)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTLINKS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllStatementLinks(SqlConnection.java:463)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1055)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTTYPES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllStatementTypes(SqlConnection.java:1142)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1056)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: STATEMENTS)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1061)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: ATTRIBUTES)
> 	at org.sqlite.core.DB.newSQLException(DB.java:890)
> 	at org.sqlite.core.DB.newSQLException(DB.java:901)
> 	at org.sqlite.core.DB.throwex(DB.java:868)
> 	at org.sqlite.core.NativeDB.prepare(Native Method)
> 	at org.sqlite.core.DB.prepare(DB.java:211)
> 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
> 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
> 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
> 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
> 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
> 	at dna.SqlConnection.getAllAttributes(SqlConnection.java:612)
> 	at dna.SqlConnection.getAllData(SqlConnection.java:1131)
> 	at dna.export.ExporterR.<init>(ExporterR.java:41)
> Data loaded: 0 statements and 0 documents.
> DNA database: test.dna
> 0 statements in 0 documents
> Statement types: 
> 
> 
>

**Comment by JBGruber** [comment]
@StefanLindow  I just saw your email. I tested your file and it looks fine to me:

```
conn <- dna_connection("/home/johannes/Documents/diss-2018-05-10.dna")

## Data loaded: 2081 statements and 64 documents.
## DNA database: /home/johannes/Documents/diss-2018-05-10.dna
## 2081 statements in 64 documents
## Statement types: DNA Statement, Annotation

nw <- dna_network(conn)

## (1/5): Processing network options... Done.
## (2/5): Filtering statements...
## 1892 out of 2081 statements retained.
## (3/5): Compiling node labels... 31 entries for the first and 403 entries for the second variable.
## (4/5): Computing network matrix... Done.
## (5/5): Retrieving results.
```

**Comment by StefanLindow** [comment]
I have the solution. It's a working directory problem. When I set the working directory in R, the rDNA-commands do not follow. I found out, because I found strange unopenable dummies of each file I tried to connect through "dna_connection"-command. So instead of the working directory of R, it uses the "/User/<name>/"-path.  (when I copied it over to that area, it works just as you posted here)

**Comment by JBGruber** [comment]
You are right. Here is code to reproduce it:

```
setwd("~/Downloads")  
library(rDNA)
dna_downloadJar()
dna_init()
setwd("..")
dna_sample()
conn <- dna_connection("sample.dna")
```

I think we could solve this by providing absolute paths to `.jnew()` . I.e., 

```
if (is.null(login) || is.null(password)) {
    export <- .jnew("dna.export/ExporterR", "sqlite", paste0(getwd(), "/", infile), "", "", verbose)
} else {
    export <- .jnew("dna.export/ExporterR", "mysql", paste0(getwd(), "/", infile), login, password, verbose)
}
```

**Comment by leifeld** [comment]
Sounds good to me.

**Comment by JBGruber** [comment]
@leifeld Can you think of any other implications this could have? `dna_init()` should not have this problem as this is where the JVM gets first started and `dna_gui()` operates independently from `dna_init()`. Anything else that tries to access files via `rJava`?

**Comment by leifeld** [comment]
Does the problem occur with `dna_gui()`? If not, why is this different? I don't think any other parts require file access.

**Comment by leifeld** [comment]
Sure, go ahead.
