### ISSUE TITLE
Installing newest beta fails

### ISSUE THREAD

**Issue by StefanLindow** [leifeld/dna#135]
I use rDNA and want to update (because it says that your dna_plotCoordinates not existing). 

`> dna_plotCoordinates(clust)`
> Error in dna_plotCoordinates(clust) : 
>  could not find function "dna_plotCoordinates"

`> sessionInfo()`
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS High Sierra 10.13.4
> 
> other attached packages:
> [1] rDNA_2.0.76     rJava_0.9-9

I get a very strange feedback (and not update takes place)

`> library("devtools")`
`> devtools::install_github("leifeld/dna/rDNA", args = "--no-multiarch")`

> Downloading GitHub repo leifeld/dna@master
> from URL https://api.github.com/repos/leifeld/dna/zipball/master
> Installing rDNA
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   '/private/var/folders/j0/_9cptvz13h18lt63y5jpwrh80000gn/T/RtmphJU0Je/devtools82fbeccf179/leifeld-dna-058652e/rDNA'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests --no-multiarch 
> 
> During startup - Warning messages:
> 1: Setting LC_TIME failed, using "C" 
> 2: Setting LC_MESSAGES failed, using "C" 
> 3: Setting LC_MONETARY failed, using "C" 
> * installing *source* package ‘rDNA’ ...
> ** R
> ** inst
> ** preparing package for lazy loading
> Error: package or namespace load failed for ‘rJava’:
>  .onLoad failed in loadNamespace() for 'rJava', details:
>   call: dyn.load(file, DLLpath = DLLpath, ...)
>   error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
>   Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
>   Reason: image not found
> Error : package ‘rJava’ could not be loaded
> ERROR: lazy loading failed for package ‘rDNA’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rDNA’
> * restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rDNA’
> Installation failed: Command failed (1)

**Comment by StefanLindow** [comment]
i just realized that you have a command for that. 

> dna_downloadJar()

anyway, you'll might wanna know about this.

**Comment by JBGruber** [comment]
I experienced something similar the other day while trying to install a different package. Any chance you still have some objects in your R environment? If rJava is still loaded (e.g., because you still have a connection to a dna database in your environment) the files R is trying to update might be locked. Open a fresh R Session, check that your environment is emtpy and try again. Maybe it might also make sense to start R from the command line instead via RStudio.

You should also be able to solve the problems with LC_TIME etc. See https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c

The command `dna_downloadJar()` downloads the external jar file. Your problem seems to be with the R package `rJava` which is independent from that.

**Comment by StefanLindow** [comment]
- starting with a fresh environment: same problem
- running R from the Terminal: same problem

as for the LC-Time thing. I figure this is for solving the lazy dl problem? Not solved through forcing R thing, and the second best option I dont understand.

**Comment by JBGruber** [comment]
Ok, I had hoped this would be easy to solve but it seems to be another rJava problem (as you might have noticed, rJava isn't the easiest package to install on macOS). These Java problems are unfortunatly really hard to debug. So here are a couple of suggestions on how to troubleshoot:

- Can you load rJava and perform the test described in the manual:

```
library("rJava")
# 1. initialize JVM
.jinit()
# 2. retrieve the Java-version
.jcall("java/lang/System", "S", "getProperty", "java.version")
# 3. retrieve JAVA_HOME location
.jcall("java/lang/System", "S", "getProperty", "java.home")
# 4. retrieve Java architecture
.jcall("java/lang/System", "S", "getProperty", "sun.arch.data.model")
# 5. retreive architecture of OS (This should have 64 in it if step 4 displays
#    "64")
.jcall("java/lang/System", "S", "getProperty", "os.arch")
```

- Could  you try to install rJava again separately: `install.packages("rJava")`?
- Could you try to run `sudo R CMD javareconf` in the terminal again?

There are a few more steps to get rJava to work on mac. Some of them are described in the manual. Maybe it helps to follow them again?

**Comment by StefanLindow** [comment]
Thing is, rJava and rDNA are running and working already.

> > library("rJava")
> > # 1. initialize JVM
> > .jinit()
> > # 2. retrieve the Java-version
> > .jcall("java/lang/System", "S", "getProperty", "java.version")
> [1] "1.8.0_171"
> > # 3. retrieve JAVA_HOME location
> > .jcall("java/lang/System", "S", "getProperty", "java.home")
> [1] "/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre"
> > # 4. retrieve Java architecture
> > .jcall("java/lang/System", "S", "getProperty", "sun.arch.data.model")
> [1] "64"
> > # 5. retreive architecture of OS (This should have 64 in it if step 4 displays
> > #    "64")
> > .jcall("java/lang/System", "S", "getProperty", "os.arch")
> [1] "x86_64"
> > 
> > 
> > install.packages("rJava")
> Error in install.packages : Updating loaded packages
> 
> Restarting R session...
> 
> > install.packages("rJava")
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rJava_0.9-9.tgz'
> Content type 'application/x-gzip' length 626627 bytes (611 KB)
> ==================================================
> downloaded 611 KB
> 
> 
> The downloaded binary packages are in
> 	/var/folders/j0/_9cptvz13h18lt63y5jpwrh80000gn/T//RtmpkCE3ji/downloaded_packages
> > 

and here is the terminal output:

> Java interpreter : /usr/bin/java
> Java version     : 1.8.0_171
> Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
> ^[[AJava compiler    : /usr/bin/javac
> Java headers gen.: /usr/bin/javah
> Java archive tool: /usr/bin/jar
> Non-system Java on macOS
> ^[[B
> trying to compile and link a JNI program 
> detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
> detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
> clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/../include/darwin  -I/usr/local/include   -fPIC  -Wall -g -O2  -c conftest.c -o conftest.o
> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
> 
> 
> JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
> Java library path: $(JAVA_HOME)/lib/server
> JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
> JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
> Updating Java configuration in /Library/Frameworks/R.framework/Resources
> Done.

**Comment by JBGruber** [comment]
> Thing is, rJava and rDNA are running and working already.

That is why I thought it must be because you still have rJava loaded. The error doesn't make particular sense to me to be honest. If rJava can be loaded under normal circumstances, why not during installation via devtools? I don't have access to a mac right now, so all I can do is google some solutions for problems which look similar. This answer on SO looks promising for example:
https://stackoverflow.com/questions/46366520/rjava-loading-error

**Comment by JBGruber** [comment]
@StefanLindow I just re-read your last comment. 

> AND IT WORKED

Do you mean the issue is resolved now? The output from `devtools::install_github("leifeld/dna/rDNA", args = "--no-multiarch")` looks like everything went fine.

**Comment by StefanLindow** [comment]
yep, the issue is resolved
