### ISSUE TITLE
dna_timeWindow

### ISSUE THREAD

**Issue by gdpark29** [leifeld/dna#138]
After updating the rDNA, my timeWindow code that previously worked does not work anymore. I remember a similar issue occurred when running for a sparse density data. Please see the code and error.

I am running the following code and receiving this error:
> mp <- dna_timeWindow(connection = conn,
                      timewindow = "months",
                      windowsize = 3,
                      method = "multipolarization",
                      duplicates = "document",
                      parallel = "PSOCK",
                      ncpus = 1)
Retrieving time window networks... Calculating Type = all 
Error in .jcall(connection$dna_connection, "[I", "getTimeWindowNumStatements",  : 
  method getTimeWindowNumStatements with signature ()[I not found

**Comment by leifeld** [comment]
Sorry, I've been busy. Will get to this asap within the next 1-2 weeks.

**Comment by leifeld** [comment]
Forgot to close this earlier. The problem was that the latest DNA JAR file version was required, but a compiled version of that hadn't been released yet at the time.
