### ISSUE TITLE
Cannot open .dna file used in version 1.3

### ISSUE THREAD

**Issue by eno1229** [leifeld/dna#139]
My dna 2.0 software cannot open the files I've created in version 1.3, and the 'import from dna file 2.0 or 1.31' options under the 'document' tab are greyed out. How can I use these files again/pull my data to rerun the analyses?

**Comment by leifeld** [comment]
You need to create a new, empty database with the standard variables first. Then the menu entry is no longer greyed out.

**Comment by eno1229** [comment]
It's telling me now that the file already exists, and that I cannot save
that as the file. So I need to create a new DNA file? I'm not exactly sure
how to do this-- I'm assuming there's a way to create a 'blank' .dna file
with the standard variables, but I cannot find instructions for this.

I also tried the 'open' DNA database option, and that also doesn't work. It
allows me to go through with making that the current file, but it doesn't
allow me to look at the coding or import any documents. What do you
recommend I do to get this to work.

**Comment by eno1229** [comment]
Yes I did, I tried to follow the steps but just didn’t get anywhere after opening the DNA software.

**Comment by JBGruber** [comment]
After opening DNA, you first need to create a new empty database using a different name than before (see Section 4.1 in the [manual](https://github.com/leifeld/dna/releases/download/v2.0-beta.21/dna-manual.pdf)). Don't change any of the options in DNA Statement etc.

After that, you can follow the steps outlined in Section 5.2.3 of the manual to import data from your old database.

If that doesn't work, could let us know which step specifically doesn't work.

**Comment by JBGruber** [comment]
Great!
