### ISSUE TITLE
Editing Statement Types from within an Existing Database

### ISSUE THREAD

**Issue by TWNorris** [leifeld/dna#140]
Is one able to edit statement types after a database has been created? When using DNA, we would like to have a "disagreement" box to go along with the already present "agreement" box. I understand how statement is intuitively formatted (i.e. if the "agreement" box isn't checked, then the person disagrees with a statement). However, I am asking if this option is possible from within an existing database for the sake of simplicity and to reduce confusion when utilizing multiple coders in DNA.

**Comment by leifeld** [comment]
Currently, you can only set up additional variables when you create a new database. We are going to add provisions for editing existing statement types in the future, but this is not the highest priority at the moment.

**Comment by TWNorris** [comment]
Thank you for your response!
