### ISSUE TITLE
Changing Qualifier Variable

### ISSUE THREAD

**Issue by Lana-Ollier** [leifeld/dna#143]
The possibility to rename the qualifier variable, using the function `dna_network`(using the argument qualifier = “agreement_renamed”)leads to a bug in the `dna_barplot()`. In the code function for `dna_barplot` will try to access `dta$agreement`, even though the variable won't exist anymore, when renamed through the `dna_network` argument qualifier. In short is there any way to change or add a qualifier variable and still use all the DNA functions? Many thanks.

**Comment by JBGruber** [comment]
That is indeed supposed to be possible. I just fixed this so please reinstall (`devtools::install_github("leifeld/dna/rDNA", args = "--no-multiarch")`) and then use:

`dna_barplot(connection, qualifier = "agreement_renamed")  `

The argument `qualifier` should now be passed on to the underlying `dna_network()`. Thanks for letting us know!
