### ISSUE TITLE
rDNA Mysql Connection

### ISSUE THREAD

**Issue by profibadan** [leifeld/dna#145]
Please I am having problem connecting to the rDNA database on a remote server. I tries using the conn  <- dna_connection function; but there is no tutorial on the arguments to incude. The function only seems to work with local sample.dna file. The Manual is of no help in this regard. It only suggests the possibility of connecting to MySQL using strings connection but no example is provided and I keep getting errors

**Comment by JBGruber** [comment]
The normal way to connect to a MySQL database looks somewhat like this:

`conn <- dna_connection("localhost/Databasename", login = "Johannes", password = "xxxxx")`

Instead of `localhost`, you might want to use the URL or IP-address of your host server instead. The function automatically assumes a MySQL database when you provide login and/or password.

Were you able to connect to the database using DNA itself? Section 4.1.2 in the manual explains how to do that. Once you are able to connect that way, you should be able to connect from rDNA as well.

If you keep experiencing issues, could you please tell us a bit more about how you are trying to connect to the database, what you were doing before (since opening the R session) and what kind of errors you get?

**Comment by profibadan** [comment]
Thanks. I was able to successfully connect to DNA on my local server. 
I have been able to connect using the example you have just provided.

**Comment by profibadan** [comment]
I have a question. In a large graph, how do we reduce the plot display. Take for instance the dna_barplot function led to the display of more than 500 items all cluttered together. Is there a way one could limit the dispaly to few items?

**Comment by JBGruber** [comment]
I assume that by reducing the plot display, you mean you want to exclude some of the statements to get a clearer plot.

With `dna_barplot()` you can do this by passing additional arguments to dna_network. From the documentation:

```
dna_network(connection, networkType = "twomode",
  statementType = "DNA Statement", variable1 = "organization",
  variable1Document = FALSE, variable2 = "concept",
  variable2Document = FALSE, qualifier = "agreement",
  qualifierAggregation = "ignore", normalization = "no",
  isolates = FALSE, duplicates = "include",
  start.date = "01.01.1900", stop.date = "31.12.2099",
  start.time = "00:00:00", stop.time = "23:59:59", timewindow = "no",
  windowsize = 100, excludeValues = list(),
  excludeAuthors = character(), excludeSources = character(),
  excludeSections = character(), excludeTypes = character(),
  invertValues = FALSE, invertAuthors = FALSE, invertSources = FALSE,
  invertSections = FALSE, invertTypes = FALSE, verbose = TRUE)
```

For example, you could use `start.date` and `stop.date` to display your data in slices. Or you could exclude authors, section, sources etc. This would look somewhat like that:

```
plot <- dna_barplot(master, start.date = "01.03.2013", stop.date = "01.01.2014")
plot
```
I was also experimenting with a `min` argument some time ago, which would exclude items that are not used at least a certain number of times. Would that be helpful in your case?

What you can also do if you just want to take a quick look at your data is to save the plot as a large pdf. This is obviously not fit for publication etc. but you can zoom in an out on your plot more easily than in the viewer pane in RStudio. Here is how you could do that:

```
library(ggplot2)
ggsave(plot = plot, filename = "big barplot.pdf", device = "pdf",
       scale = 2, width = 15, height = 150, units = "cm",
       dpi = 600, limitsize = FALSE)
```

**Comment by profibadan** [comment]
Thanks so much

**Comment by profibadan** [comment]
> I assume that by reducing the plot display, you mean you want to exclude some of the statements to get a clearer plot.
> 
> With `dna_barplot()` you can do this by passing additional arguments to dna_network. From the documentation:
> 
> ```
> dna_network(connection, networkType = "twomode",
>   statementType = "DNA Statement", variable1 = "organization",
>   variable1Document = FALSE, variable2 = "concept",
>   variable2Document = FALSE, qualifier = "agreement",
>   qualifierAggregation = "ignore", normalization = "no",
>   isolates = FALSE, duplicates = "include",
>   start.date = "01.01.1900", stop.date = "31.12.2099",
>   start.time = "00:00:00", stop.time = "23:59:59", timewindow = "no",
>   windowsize = 100, excludeValues = list(),
>   excludeAuthors = character(), excludeSources = character(),
>   excludeSections = character(), excludeTypes = character(),
>   invertValues = FALSE, invertAuthors = FALSE, invertSources = FALSE,
>   invertSections = FALSE, invertTypes = FALSE, verbose = TRUE)
> ```
> For example, you could use `start.date` and `stop.date` to display your data in slices. Or you could exclude authors, section, sources etc. This would look somewhat like that:
> 
> ```
> plot <- dna_barplot(master, start.date = "01.03.2013", stop.date = "01.01.2014")
> plot
> ```
> I was also experimenting with a `min` argument some time ago, which would exclude items that are not used at least a certain number of times. Would that be helpful in your case?
> 
> What you can also do if you just want to take a quick look at your data is to save the plot as a large pdf. This is obviously not fit for publication etc. but you can zoom in an out on your plot more easily than in the viewer pane in RStudio. Here is how you could do that:
> 
> ```
> library(ggplot2)
> ggsave(plot = plot, filename = "big barplot.pdf", device = "pdf",
>        scale = 2, width = 15, height = 150, units = "cm",
>        dpi = 600, limitsize = FALSE)
> ```

When I tried the code: 
library(ggplot2)
ggsave(plot = plot, filename = "big barplot.pdf", device = "pdf",
       scale = 2, width = 15, height = 150, units = "cm",
       dpi = 600, limitsize = FALSE)
I got this error:

Error in UseMethod("grid.draw") : 
  no applicable method for 'grid.draw' applied to an object of class "function"

**Comment by profibadan** [comment]
> I assume that by reducing the plot display, you mean you want to exclude some of the statements to get a clearer plot.
> 
> With `dna_barplot()` you can do this by passing additional arguments to dna_network. From the documentation:
> 
> ```
> dna_network(connection, networkType = "twomode",
>   statementType = "DNA Statement", variable1 = "organization",
>   variable1Document = FALSE, variable2 = "concept",
>   variable2Document = FALSE, qualifier = "agreement",
>   qualifierAggregation = "ignore", normalization = "no",
>   isolates = FALSE, duplicates = "include",
>   start.date = "01.01.1900", stop.date = "31.12.2099",
>   start.time = "00:00:00", stop.time = "23:59:59", timewindow = "no",
>   windowsize = 100, excludeValues = list(),
>   excludeAuthors = character(), excludeSources = character(),
>   excludeSections = character(), excludeTypes = character(),
>   invertValues = FALSE, invertAuthors = FALSE, invertSources = FALSE,
>   invertSections = FALSE, invertTypes = FALSE, verbose = TRUE)
> ```
> For example, you could use `start.date` and `stop.date` to display your data in slices. Or you could exclude authors, section, sources etc. This would look somewhat like that:
> 
> ```
> plot <- dna_barplot(master, start.date = "01.03.2013", stop.date = "01.01.2014")
> plot
> ```
> I was also experimenting with a `min` argument some time ago, which would exclude items that are not used at least a certain number of times. Would that be helpful in your case?
> 
> What you can also do if you just want to take a quick look at your data is to save the plot as a large pdf. This is obviously not fit for publication etc. but you can zoom in an out on your plot more easily than in the viewer pane in RStudio. Here is how you could do that:
> 
> ```
> library(ggplot2)
> ggsave(plot = plot, filename = "big barplot.pdf", device = "pdf",
>        scale = 2, width = 15, height = 150, units = "cm",
>        dpi = 600, limitsize = FALSE)
> ```

**Comment by profibadan** [comment]
When I tried the code:
library(ggplot2)
ggsave(plot = plot, filename = "big barplot.pdf", device = "pdf",
scale = 2, width = 15, height = 150, units = "cm",
dpi = 600, limitsize = FALSE)
I got this error:

Error in UseMethod("grid.draw") :
no applicable method for 'grid.draw' applied to an object of class "function"

**Comment by profibadan** [comment]
Also When I ran this code: 
plot <- dna_barplot(master, start.date = "01.03.2013", stop.date = "01.01.2014")
plot

I got this error: 

Error in .jcall(connection$dna_connection, "V", "rNetwork", networkType,  : 
  object 'master' not found

**Comment by JBGruber** [comment]
> no applicable method for 'grid.draw' applied to an object of class "function"

This means that there is no object `plot` that could be saved. You need to create a plot first. The reason  for the strange error message is that `plot` is also the name of a function. Usually you should not name an object the same as a function for this exact reason (my fault).

> object 'master' not found

Basically the same problem. In this case, `master` was my connection to a database. You would need to use the object which is your connection. In the manual, we usually called this object `conn`.
