### ISSUE TITLE
New error message when loading connections

### ISSUE THREAD

**Issue by MarleneKammerer** [leifeld/dna#146]
Dear all
I have encountered a new error message when loading the connections into R:

> conn <- dna_connection("COMPON-Switzerl_Level3_aggregated_20190121_new_Marlene.dna")
Data loaded: 479 statements and 126 documents. Error in .jcall(x$dna_connection, "S", "rShow") :    method rShow with signature ()Ljava/lang/String; not found.

My research assisstant and I both get the same message on two different computers. On Friday, using the same code, it worked. Later it didn't anymore. We also made sure that we use the latest rdna version.

See the attached file for the full R output and session Info.

Thank you for your help.
Marlene

[Issue_DNA_git-hub.txt](https://github.com/leifeld/dna/files/2803383/Issue_DNA_git-hub.txt)

**Comment by JBGruber** [comment]
I'm afraid that the `R` package and the most recent `.jar` file are out of sync at the moment (a new version should be published soon).
@leifeld has, however, created a GNU makefile, which should make compilation of the `.jar` from source very easy, if all necessary software is installed. Just in case, I'm I'm attaching the newest `.jar` here but for future reference:

1. Clone git repository to your local drive with `git clone https://github.com/leifeld/dna.git` in your terminal.
2. Change directory to the newly created folder: `cd dna`
3. Use make to create all binary files (`make all`) or just the `.jar` file: `make dna`
4. Take the `.jar` file from the newly create `output` folder and place it in your working directory.
5. In `R`, call `dna_init()` and check if connection to `dna-2.0-beta23.jar` worked.

Or take this file instead:
[dna-2.0-beta23.zip](https://github.com/leifeld/dna/files/2803557/dna-2.0-beta23.zip)

Hope this solves your problem. Let us know if anything else comes up.

**Comment by leifeld** [comment]
Thanks @JBGruber. For future reference, it's also possible to download the rDNA source package that matches the latest released jar file from the [releases](https://github.com/leifeld/dna/releases) page. The jar file and the rDNA version should always come from the same release, and if non-release versions are installed from source, it is necessary to install/download both the current jar file and the current rDNA version for maximal compatibility.

**Comment by JBGruber** [comment]
The problem is though that `devtools::install_github()` will install from the newest source.

To install from the latest release, you would need:
```
devtools::install_url("https://github.com/leifeld/dna/releases/download/v2.0-beta.22/rDNA_2.1.9.tar.gz", INSTALL_opts = "--no-multiarch")
```
Maybe it would make sense to add this command as a note to current and future releases or on the readme page?
