### ISSUE TITLE
Change "using events" to "using statments" in "Moving time window" option

### ISSUE THREAD

**Issue by JBGruber** [leifeld/dna#168]
Change "using events" to "using statments" in "Moving time window" option in the export window of DNA and in `dna_network`. It is confusing otherwise. Unless there is a specific reason for the terminology.

**Comment by leifeld** [comment]
I have been thinking about this, and I think `events` actually makes sense because this is the terminology I use in my paper on smoothed bipolarization. I will close the issue.
