### ISSUE TITLE
Small font on high resolution screens

### ISSUE THREAD

**Issue by JBGruber** [leifeld/dna#169]
The font size appears extremely small in DNA on high-resolution displays. That's not a huge problem for reading the document's text, but the menus and other windows (like document selection) are hard to use.

**Comment by leifeld** [comment]
Perhaps related to [this](https://bugs.openjdk.java.net/browse/JDK-8180815) bug in Java. The second proposed solution there might possibly work. Tbc.

**Comment by leifeld** [comment]
I opened related Stackoverflow questions [here](https://stackoverflow.com/questions/67350606/) and [here](https://stackoverflow.com/questions/70672430/), without answers as of now. It must be an instance of the JDK bug referenced above. The problem persists in DNA 3.0. There is currently no solution other than scaling the application from the command line, as mentioned in one of the comments to the StackOverflow questions, but even that does not work extremely well. DNA does offer larger font sizes for editing, but that does not affect the remaining window components. I will close the issue for now.
