### ISSUE TITLE
Two-mode "combine" visualisation with dna_plotNetwork in red, green, and blue

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#170]
Two-mode network visualizations using `dna_plotNetwork` are currently displayed in one single color, even when the `combine` qualifier aggregation is used, which should display the edges in red (for conflict), green (for congruence), and blue (mixed). Note that integer qualifiers may produce a high number of combinations that cannot be readily mapped into these three colors.

**Comment by JBGruber** [comment]
See the answer [here](https://github.com/leifeld/dna/issues/197#issuecomment-659667135) for working code that we can build on.

**Comment by leifeld** [comment]
Tagging @TimHenrichsen

**Comment by leifeld** [comment]
This was done in some update in the meantime.
