### ISSUE TITLE
Search function not working with different sorting (DNA)

### ISSUE THREAD

**Issue by JBGruber** [leifeld/dna#174]
Using the search function I just realized that DNA will ignore the sorting of the documents. Meaning that when documents are sorted by date (default), searching for a keyword will jump to the right position but if documents are sorted by, for example, ID the search will jump to a wrong document.

![2019-03-05_17-33-22](https://user-images.githubusercontent.com/23524101/53825078-5ade1600-3f6d-11e9-806d-4a991390b748.gif)

**Comment by leifeld** [comment]
New search function added to DNA 3.0 in commit e626ab5f27f4514dcefd2f9388f81cc8e52775ad, also fixing the bug described above.
