### ISSUE TITLE
Having problems with rlang dependency

### ISSUE THREAD

**Issue by Periloux** [leifeld/dna#176]
Currently struggling with installing rDNA. Ive gone through thnava install and rJava install and everything checks out. Ive also:

- updated R and RStudio. 
- deleted the original rlang package and attempted to reinstall it
- updated every package within R.

Hopefully you can help.

`> install_github("leifeld/dna/rDNA@v2.0-beta.24", INSTALL_opts = "--no-multiarch")
Downloading GitHub repo leifeld/dna@v2.0-beta.24
These packages have more recent versions available.
Which would you like to update?

1:   rlang (0.3.1 -> 0.3.2) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: y
1: 1
Invalid input, please try again
1: 1
rlang (0.3.1 -> 0.3.2) [CRAN]
Installing 1 packages: rlang

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.3.1  0.3.2              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.3.2.tar.gz'
Content type 'application/x-gzip' length 858244 bytes (838 KB)
==================================================
downloaded 838 KB

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rlang’
Error in i.p(...) : 
  (converted from warning) installation of package ‘rlang’ had non-zero exit status`

**Comment by leifeld** [comment]
Hi. Can you press "n" when prompted to update `rlang` and report if there is any problem? Thanks.

**Comment by Periloux** [comment]
**Here, I opted to not update rlang**

> devtools::install_github("leifeld/dna/rDNA", INSTALL_opts = "--no-multiarch")
Downloading GitHub repo leifeld/dna@master
These packages have more recent versions available.
Which would you like to update?

1:   rlang (0.3.1 -> 0.3.2) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 
✔  checking for file ‘/private/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T/RtmpgGcKGe/remotese42f3d0d3b27/leifeld-dna-32f1173/rDNA/DESCRIPTION’ ...
─  preparing ‘rDNA’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rDNA_2.1.17.tar.gz’
   
* installing *source* package ‘rDNA’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘rDNA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rDNA’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T//RtmpgGcKGe/filee42f3af7dfc8/rDNA_2.1.17.tar.gz’ had non-zero exit status


**Here, I pressed the "N" when prompted to choose the binary option**


> devtools::install_github("leifeld/dna/rDNA", INSTALL_opts = "--no-multiarch")
Downloading GitHub repo leifeld/dna@master
These packages have more recent versions available.
Which would you like to update?

1:   rlang (0.3.1 -> 0.3.2) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
rlang (0.3.1 -> 0.3.2) [CRAN]
Installing 1 packages: rlang

  There is a binary version available but the source version is later:
      binary source needs_compilation
rlang  0.3.1  0.3.2              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) n
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/rlang_0.3.1.tgz'
Content type 'application/x-gzip' length 1122574 bytes (1.1 MB)
==================================================
downloaded 1.1 MB


The downloaded binary packages are in
	/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T//RtmpgGcKGe/downloaded_packages
✔  checking for file ‘/private/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T/RtmpgGcKGe/remotese42f274b70c6/leifeld-dna-32f1173/rDNA/DESCRIPTION’ ...
─  preparing ‘rDNA’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rDNA_2.1.17.tar.gz’
   
* installing *source* package ‘rDNA’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘rDNA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rDNA’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T//RtmpgGcKGe/filee42f4637520e/rDNA_2.1.17.tar.gz’ had non-zero exit status

**Comment by JBGruber** [comment]
It looks like you are having two different issues there. I wouldn't worry at the moment about `rlang`. Just wait until the new binary version comes out. Then you should be able to update it.

The second problem seems to be an issue with `rJava`. Can you run these commands from the manual to make sure `rJava` is configured correctly:

```
library("rJava")
# 1. initialize JVM
.jinit()

# 2. retrieve the Java-version
.jcall("java/lang/System", "S", "getProperty", "java.version")

# 3. retrieve JAVA_HOME location
.jcall("java/lang/System", "S", "getProperty", "java.home")

# 4. retrieve Java architecture
.jcall("java/lang/System", "S", "getProperty", "sun.arch.data.model")

# 5. retreive architecture of OS (This should have 64 in it if step 4 displays
# "64")
.jcall("java/lang/System", "S", "getProperty", "os.arch")

# 6. retrieve architecture of R as well (This should again have 64 in it if
# step 4 and 5 display 64)
R.Version()$arch
```

Depending on your operating system, you might need to run`R CMD javareconf` in the terminal again after an update (if you use MacOS or Linux). See the install chapter in the manual if you don't know how to do that.

**Comment by Periloux** [comment]
```
> library("rJava")
> # 1. initialize JVM
> .jinit()
> # 2. retrieve the Java-version
> .jcall("java/lang/System", "S", "getProperty", "java.version")
[1] "1.8.0_202"
> # 3. retrieve JAVA_HOME location
> .jcall("java/lang/System", "S", "getProperty", "java.home")
[1] "/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre"
> # 4. retrieve Java architecture
> .jcall("java/lang/System", "S", "getProperty", "sun.arch.data.model")
[1] "64"
> # 5. retreive architecture of OS (This should have 64 in it if step 4 displays
> # "64")
> .jcall("java/lang/System", "S", "getProperty", "os.arch")
[1] "x86_64"
> # 6. retrieve architecture of R as well (This should again have 64 in it if
> # step 4 and 5 display 64)
> R.Version()$arch
[1] "x86_64"
```

**Comment by JBGruber** [comment]
It looks to me like you are using macOS. What did `R CMD javareconf` return for you?

**Comment by leifeld** [comment]
Has there been a resolution? Can we close this issue?

**Comment by Periloux** [comment]
Sorry for the delay, I've been in conferences the past few weeks. This was the return from running the 
R CMD javareconf


> 

Perilouxs-MacBook-Pro:~ pcpeay$ R CMD javareconf
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Java interpreter : /usr/bin/java
Java version     : 1.8.0_202
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

trying to compile and link a JNI program
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L/Users/pcpeay/Library/Java/Extensions -L/Library/Java/Extensions -L/Network/Library/Java/Extensions -L/System/Library/Java/Extensions -L/usr/lib/java -L. -ljvm
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Unable to compile a JNI program


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre
Java library path:
JNI cpp flags    :
JNI linker flags :
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.



I also attempted to run it from the R terminal and received the same error as before.

> remotes::install_github("leifeld/dna/rDNA@*release", INSTALL_opts = "--no-multiarch")
Downloading GitHub repo leifeld/dna@v2.0-beta.24
   checking DESCRIPTION meta-information ...7/l85dyfvj4sjfm466fb3krr4h0000gn/T/Rtmpoz75TP/remotesc51c2eb646ad/leifeld-dna-a625354/rDNA/DESCRIPTION’ ...
* installing *source* package ‘rDNA’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘rDNA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rDNA’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/c7/l85dyfvj4sjfm466fb3krr4h0000gn/T//Rtmpoz75TP/filec51c18f4e154/rDNA_2.1.16.tar.gz’ had non-zero exit status

**Comment by leifeld** [comment]
No problem! To me, it looks like `rJava` cannot be installed because there is an issue with `XCode` on your Mac. Can you check out [this solution](https://apple.stackexchange.com/questions/254380/) and report back?

**Comment by leifeld** [comment]
If that doesn't work, can you also try [this](https://stackoverflow.com/a/46678478/1566598)?

**Comment by leifeld** [comment]
Can we close this, or are there any follow-up questions?
