### ISSUE TITLE
PlotDendro

### ISSUE THREAD

**Issue by profibadan** [leifeld/dna#177]
The default plotDendro is limited to only 6 discrete values. I tris to run the dna_plotDendro(clust,....) coord_flip() program but I got this warning message

Warning messages:
1: The shape palette can deal with a maximum of 6 discrete values because more than 6 becomes
difficult to discriminate; you have 12. Consider specifying shapes manually if you must have
them.

How do I increase the shapes to 12?

**Comment by JBGruber** [comment]
You give little information on what your settings are and what you are trying to do. Based on the error I assume you tried something like this:

```
library(rDNA)
dna_init()
conn <- dna_connection(dna_sample())

clust <- dna_cluster(conn, variable1 = "person")

dna_plotDendro(clust, leaf_ends = "attribute2")
```
If you really want to have more than 6 shapes, you need to add them with the argument `custom_shapes`. Here is the description from the help file:

> If shapes are provided, those are used for leaf_ends instead of the standard ones. Available shapes range from 0:25 and 32:127.

So you could plot more shapes with, for example:

```
dna_plotDendro(clust, leaf_ends = "attribute2", custom_shapes = 0:11)
# or
dna_plotDendro(clust, leaf_ends = "attribute2", custom_shapes = c(1:6, 32:38))
```
![dna](https://user-images.githubusercontent.com/23524101/54886867-be7ca480-4e84-11e9-8ecf-d3a361b3d606.png)

**Comment by profibadan** [comment]
Thanks for the response. Here are my codes:

library("ggplot2")

dna_plotDendro(clust,
               activity = TRUE,
               shape = "diagonal",
               truncate = 20,
               leaf_colours = "attribute1",
               colours = "brewer",
               custom_colours = "Set1",
               rectangles = "#e34a33",
               leaf_ends = "attribute2",
               ends_alpha = 0.8,
               font_size = 9,
               leaf_labels = "ticks") +
  coord_flip()

**Comment by JBGruber** [comment]
Does the suggestion from above work for you?

**Comment by profibadan** [comment]
Yes, thanks but I also got this error while plotting another denogram:

Warning message:
In RColorBrewer::brewer.pal(n, pal) :
  n too large, allowed maximum for palette Set2 is 8
Returning the palette you asked for with that many colors.

Here is the code:
dna_plotDendro(clust,
               circular = TRUE,
               leaf_colours = "attribute2",
               leaf_labels = "nodes",
               colours = "brewer",
               custom_colours = "Set2",
               theme = "void")

I have 12 Organisation Types but the colour limit is 8. How can I manually set the colour hexadecimal

**Comment by JBGruber** [comment]
Set `colours = "manual"` and provide the right number of `custom_colours` in a vector:
```
dna_plotDendro(clust, leaf_colours = "attribute2", 
               colours = "manual",
               custom_colours = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", 
                                  "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00",
                                  "#CAB2D6", "#6A3D9A", "#FFFF99", "#B15928"))
```

Or use a `brewer` set with enough colors:

```
dna_plotDendro(clust, leaf_colours = "attribute2", 
               colours = "brewer",
               custom_colours = "Paired")
```

**Comment by profibadan** [comment]
Thanks once again. There is this issue with the heatmap plot (see the attached)
How do I increase the length and breadth of the of the Blue area
![plotheatmapsample](https://user-images.githubusercontent.com/8397764/54917954-e4419200-4ef4-11e9-86bf-a9e97b9bde53.png)

**Comment by JBGruber** [comment]
Not entirely sure what you want to do. For really big heatmaps, I like to save them as a pdf since it's easier to zoom in and out. I see that your labels are clipped but I don't know under which circumstances this would happen. The dedrogram is also quite far from the heatmap, which is not the case when I use the function. 

For big heatmaps, I prefer to save them as a PDF to inspect them as it is easier to zoom in and out. The command `ggsave` is excellent for this, I think. So with a big heatmap, I would use this code:

```
g <- dna_plotHeatmap(clust.l)

ggplot2::ggsave(plot = g, 
                filename = "big heatmap.pdf", 
                device = "pdf", 
                path = NULL,
                scale = 2, 
                width = 15, 
                height = 150, 
                units = "cm",
                dpi = 600, 
                limitsize = FALSE)
```

You might need to play around with `scale`, `width`, `height` a bit since your data looks different from mine.

**Comment by profibadan** [comment]
Thanks. The instructions work with  PDF
