### ISSUE TITLE
Can't import documents

### ISSUE THREAD

**Issue by AnnaKuk** [leifeld/dna#182]
Hi Philip,

I just downloaded the latest version of DNA. When I go to the Documents tab to import my raw data, I can't click on any of the options as they are all light grey. What should I do?

Best, Anna

**Comment by JBGruber** [comment]
Did you open a database before trying to import documents?

**Comment by AnnaKuk** [comment]
Oh, I didn't realize that I have to do that first. Thanks a lot!

**Comment by JBGruber** [comment]
No worries. In case you have more questions, it might help to check out our [manual](https://github.com/leifeld/dna/releases/download/v2.0-beta.24/dna-manual.pdf). Have fun coding :smiley:
