### ISSUE TITLE
Network Plots by Person 

### ISSUE THREAD

**Issue by TWNorris** [leifeld/dna#183]
In section 8.6 of the DNA Manual, the network plots shown are based on organization. My question is if you can make these network plots using "person" instead of "organization." If so, what would be the steps I need to make these plots?

**Comment by JBGruber** [comment]
Checking `?dna_network` you can see that there are arguments for `variable1` and `variable2`:

``` r
library(rDNA)
dna_init()
conn <- dna_connection(dna_sample())

nw <- dna_network(conn,
                  variable1 = "person",
                  variable2 = "concept",
                  networkType = "onemode",
                  qualifierAggregation = "congruence",
                  duplicates = "document",
                  excludeValues = list("concept" =
                                         "There should be legislation to regulate emissions."))

dna_plotNetwork(nw, layout = "mds", show_legend = FALSE)
```

![](https://i.imgur.com/IQvp7ZK.png)
