### ISSUE TITLE
Example calculation of edge weight in the manual

### ISSUE THREAD

**Issue by palmeida** [leifeld/dna#186]
In page 6 of the manual, section 2.3.1, Congruence networks, there is an example of calculation of an edge weight:

2 x 3 x (1 - | -4 - 2 |/ 11 -1) = 4.2

Shouldn't it be 2.4? This is the same as 2 x 3 x 0.4, right? It's a minor issue, but I was trying to understand the formula and wanted to make sure I'm not getting something wrong, or making a basic error in math.

**Comment by leifeld** [comment]
Thanks for pointing out the error. I have fixed it in the code base for the next release (which I am hoping to release in a few weeks).
