### ISSUE TITLE
New version of `ggraph` changes `dna_plotNetwork` behaviour and breaks `dna_plotHive`

### ISSUE THREAD

**Issue by JBGruber** [leifeld/dna#188]
The development version of `ggraph` (`remotes::install_github("thomasp85/ggraph"`) contains some changes that might be/are relevant for `rDNA`. I compiled the manual and noticed three things:

1. `ggraph` is now also using the [`graphlayouts`](https://github.com/schochastics/graphlayouts) package, which provides some extra layouts.
2. The default layout has changed from `nicely` to `stress`.
before:
![image](https://user-images.githubusercontent.com/23524101/63835825-94219c80-c978-11e9-8dab-858e7c90146d.png)
after:
![image](https://user-images.githubusercontent.com/23524101/63835810-8a983480-c978-11e9-84f3-22f618ed8519.png)
3. Most importantly, it looks like the hive layout has changed, which breaks `dna_plotHive`:
![image](https://user-images.githubusercontent.com/23524101/63836025-04c8b900-c979-11e9-9b61-adb683513dfc.png)

1 + 2 seems great, we only have to check the help file if something needs to be changed. 3. is a problem and I'll try to have a look at fixing it as soon as I can.

**Comment by JBGruber** [comment]
I had a quick look at `dna_plotHive` and it turns out the issue was very easy to solve. It's not the most elegant solution as we now have two different layout commands depending on the installed version of `ggraph` but it seems to work fine. I leave this open for discussion and since we might have to update the documentation for `dna_plotNetwork`.

**Comment by leifeld** [comment]
Looks good to me, thanks. More importantly, this also fixes #179. Can you check if there are additional layouts we should add to the layout argument, now that `graphlayouts` is used?

**Comment by leifeld** [comment]
The next DNA tutorial workshop is next week. Would be great if we could close this issue until then. I will also work on a few other things. Ideally, I'd like to release a new version after the weekend. Thx.

**Comment by JBGruber** [comment]
I looked through the documentation and changed the explanation of layout where necessary in the manual and in `rDNA`. Besides "stress", there is one more layout from `graphlayouts` that works out of the box:

``` r
library(rDNA)
dna_init()
#> Jar file: /home/johannes/R/x86_64-pc-linux-gnu-library/3.6/rDNA/extdata/dna-2.0-beta25.jar
conn <- dna_connection(dna_sample())
nw <- dna_network(conn, networkType = "onemode")
dna_plotNetwork(nw, "focus", focus = 2)
```

![](https://i.imgur.com/XaBzUtY.png)

Other layout would require more work. I added "focus" to the examples in the `dna_plotNetwork` documentation.

Have a look at the commit, I think the issue can be closed.

**Comment by leifeld** [comment]
Fantastic, thanks! Have you added `focus` to the manual as well?

**Comment by JBGruber** [comment]
I added `focus` to the list of available layouts in the manual. I also noticed that the command would fail when `layout = "focus"` but no focus was provided, so I added a default for that case. Should be ready for the release now.

**Comment by leifeld** [comment]
Good stuff. Thanks!
