### ISSUE TITLE
I cannot load the rDNA package

### ISSUE THREAD

**Issue by mlozano85** [leifeld/dna#193]
Hi!
I hope you are doing well...

I've been trying to download the rDNA package on Rstudio, as well as the other packages recommended:
install.packages("statnet")
install.packages("xergm")
install.packages("igraph")
install.packages("cluster")
install.packages("rJava")
install.packages("remotes") 
install.packages("rDNA")

I get the following error when I try to install the rDNA package. I have tried many different R versions, and I always get the same error. 
**Warning in install.packages :
  package ‘rDNA’ is not available (for R version 3.5.3)**

I have also tried:
**install.packages("remotes") 
remotes::install_github("leifeld/dna/rDNA@*release", INSTALL_opts = "--no-multiarch")**
and get the following error:
**Error: Failed to install 'rDNA' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’**

The other packages give me either the same error or something like this:
**Warning in install.packages :
  installation of package ‘statnet’ had non-zero exit status**

I have tried this using a mac and a windows computer. I get the same errors. 

How can this be fixed? or what specific R version should I use?

Thanks!!!!

**Comment by leifeld** [comment]
Hi there! The `install_github` command is the right way of doing it. Can you confirm that the installation of the `remotes` package worked out? It also sounds like the installation of the dependencies, including `statnet` didn't work out. If that's the case, I'd recommend fixing the installation of `statnet` first before proceeding with `rDNA`.

**Comment by mlozano85** [comment]
Thanks for your reply! I managed to install the remotes and statnet packages. However, the rDNA package installation is still not working. What I find strange is that I tried to run the same script on rstudio.cloud, and the installation of the rDNA package works there. I guess for now I will work on there. But would be nice to know why this doesnt work on RStudio. Thanks!

**Comment by JBGruber** [comment]
You might want to check out the installation section in the [manual](https://github.com/leifeld/dna/releases/download/v2.0-beta.24/dna-manual.pdf). The steps for Windows and Linux should work, [the steps for macOS are currently outdated](https://github.com/leifeld/dna/issues/192).

The reason why rDNA works smoothly on rstudio.cloud is that `rJava` is set up correctly there by default. Setting this up can be frustrating on some operating systems (especially macOS!).

**Comment by mlozano85** [comment]
Thanks for your reply... I understand now the problem. I have a macOS, so I'll just continue working on the rstudio.cloud. Thanks for the help!

**Comment by leifeld** [comment]
I'd be very interested in finding a solution for this, but I don't have a Mac with macOS Catalina to try it out and find a solution. It used to work in earlier macOS versions. There are some resources on the web with hints that one could try out. For example, [this](https://www.owsiak.org/r-java-11-and-making-sure-you-can-load-rjava/) (if you'd like to give it a try).

**Comment by leifeld** [comment]
A new version of `rJava` was released on CRAN on 24 March 2020. I don't know if it solves any of the problems on a Mac. But perhaps worth a try.
