### ISSUE TITLE
dna.density problems

### ISSUE THREAD

**Issue by DelpyLeo** [leifeld/dna#195]
Hi ! 
I have problems with the dna.density command.
I think the command underestimates my density matrix
I have a directed and weighed network and I want a density matrix by "Block" :

dna.density(mat, partitions = blks$Block, weighted = TRUE,  verbose = FALSE)

Are there other parameters to adjust?

Many thanks !

**Comment by leifeld** [comment]
Hi there. The `dna.density` function is from rDNA 1.32. This version has not been updated over the last seven years, and the function is unfortunately not part of the package anymore. The `master` branch here on GitHub contains the most recent beta of rDNA 2.0.

**Comment by DelpyLeo** [comment]
Thank you for your quick reply. I will find another way
