### ISSUE TITLE
Question about cluster analysis and dendrogram

### ISSUE THREAD

**Issue by marijswinkels** [leifeld/dna#196]
Hey! I'm trying to create different cluster analyses (for variable "person") for the timeframes I'm researching. However, when I'm using the timeframe arguments, the cluster analysis also takes in all the people that do not make statements in the set timeframe. I can think of a manual way to work around this (using excludeValues), but that will take a lot of time for the 5 timeframes that I'm studying, and more than > 180 persons that are in the dataset. Below is an example of the code I'm using. What argument can I use to exclude those persons? 

clustf0 <- dna_cluster(conn, variable1 = "person", transpose = FALSE, collate = FALSE,
                     duplicates = "include", clust.method = "ward.D2",
                     attribute1 = "value", attribute2 = "type", cutree.k = 5, dimensions = 2, qualifier = "agreement",
                     normalization = "prominence", start.date = "01.01.2000", stop.date = "21.10.2009")

**Comment by leifeld** [comment]
Many of the analysis functions have an `include.isolates = FALSE` argument, but I'm not sure if `dna_cluster` does. Alternatively, there are several other functions for clustering, including `dna_dendrogram`. Have you tried that one as well? If you don't need a dendrogram, you can use the underlying `dna_multiclust` function. Both functions apply a range of different clustering techniques and then select the best-fitting one according to modularity (or you can select the method you'd like).
