### ISSUE TITLE
Normalization in two-mode-network with "combine" qualifier aggregation possible?

### ISSUE THREAD

**Issue by LZnsr** [leifeld/dna#199]
Hi everyone, 

I am looking at two-mode-networks from my coded DNA database at the moment.

However, in the export data window, it is not possible to use the "normalization" setting (it only shows "no" as default and only option) when the two-mode and the "combine" qualifier aggregation options are selected.
What is the reason for that? 
Is it because of the "translation" into qualitative categories?
Or should it normally work with the otherwise available options of "activity" and "prominence" within the other two-mode and aggregation settings.

Btw: I am using the dna-2.0-beta25-Version.

I am looking forward to your advice!

Thank you!

**Comment by leifeld** [comment]
That's right. Normalization would not make any sense with two-mode networks and the `combine` setting. With that setting, you no longer take into account the actual number of concepts or mentions, i.e., you convert the counts into three categories, yes, no, and both. Normalization is about those frequencies, though, so it wouldn't make sense to apply it. Switch to a one-mode network with `congruence` or `subtract` settings or to a two-mode network with `subtract`, and it should offer you some options. Make sure you read Chapter 2 of the _DNA Manual_ to get an idea of what the different kinds of normalization do, and perhaps also the chapter in the _Oxford Handbook of Political Networks_.
