### ISSUE TITLE
dna_network function error

### ISSUE THREAD

**Issue by JKerms89** [leifeld/dna#203]
Hi,

I am trying to retrieve data from DNA using the dna_network(conn) function. However I receive the following error message:

Error in .jcall(connection$dna_connection, "V", "rNetwork", networkType,  : 
  method rNetwork with signature (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I not found

I receive this message even when I try to import the dna.sample dataset. Can anyone kindly help me. Many thanks,

Jan

**Comment by leifeld** [comment]
Hi there. Can you provide a minimal self-contained example, please?

Are you using the latest release versions of DNA and rDNA? (The current master branch version may be incompatible with the release version of DNA.)

Do other rDNA functions, such as dna_gui, work?

Does any of the code from chapter 8 of the manual work?

What version number of Java are you using? It needs to be 1.8 at least. You can also use rDNA on RStudio Cloud if there are any local installation issues.

**Comment by JKerms89** [comment]
Hi there. Thank you for your prompt reply. I reinstalled Java and rDNA and everything is working seamlessly with the sample dataset. However, I now want to import my own sample dataset and I receive the following error message: 

Error in .jcall(connection$dna_connection, "[[D", "getMatrix", simplify = TRUE) : 
  java.lang.Exception: Variable 1 ('organization') does not exist in this statement type.

I guess I receive this message as my variables have different names. How can I modify the function so that the dna_network function works with my dataset?

Many thanks in advance of your further assistance.

**Comment by leifeld** [comment]
You will need to tell the `dna_network` function that your data structure looks different. To do so, use the `statementType` argument to tell the function which kind of statement type your analysis should be based on, and then use the corresponding variable names in the `variable1`, `variable2`, and `qualifier` arguments. See the help page in `R` for the `dna_network` function, which is accessible if you type `?dna_network`.

**Comment by JKerms89** [comment]
I managed to work it out myself, but many thanks for helping me! :) 

Best wishes
