### ISSUE TITLE
Integer variables using the DNA analyzer

### ISSUE THREAD

**Issue by JKerms89** [leifeld/dna#204]
Hi Philip,

I have an integer variable containing -1 (negative), 0 (neutral) and +1 (positive) statements. In would like to know if you can code for statements which are neither positive or negative in DNA? I would like to use the integer as agreement/disagreement qualifier. Is this possible? If not, can you advise how I can code for concepts which are neither used positively or negatively? Many thanks.

**Comment by leifeld** [comment]
Yes, you can do it that way. Chapter 2 of the manual contains details on how this is dealt with during network construction. But I have yet to come across a case where neutral statements would make substantive sense for identifying coalitions. It's common practice to define a statement as a text portion that expresses agreement or disagreement of an actor with a concept. Neutral statements do not contain such information and would not add structure to the network. But yes, from a technical and mathematical perspective it is possible.

**Comment by JKerms89** [comment]
Thank you for this! All the best.
