### ISSUE TITLE
Cannot code new DNA statements

### ISSUE THREAD

**Issue by raulgtzmeave** [leifeld/dna#205]
Hi all!

I've been working perfectly for the last few months on my thesis project. All of the sudden, today, when I want to code a new DNA statement the software only underlines the declaration, but does not display the menu to capture the information (actor, organization, statement). The statement seems to appear (because the text is underlined), but it doesn't allow me to see what it is about. 

Also, I can see the DNA statements that I had coded before and the menu is displayed correctly, It just doesn't happen for the new ones.

I'm using DNA 2.0 beta 25.

Hope you guys can help me out.

Thanks

**Comment by raulgtzmeave** [comment]
I forgot to mention that I can see the DNA statements that I had coded (the menu is displayed correctly), It just doesn't happen with the new ones.

**Comment by leifeld** [comment]
Hi there. I assume there must have been file system access error (i.e., the software couldn't read everything from the database or write everything into the database), leaving you with some incomplete statements or other data. But not sure.

I would suggest opening the database using the [DB Browser for SQLite](https://sqlitebrowser.org/) and finding and fixing the inconsistency. If you can't do that, you can send me a copy of your file by email, and I can take a look and see if I can fix it.

As a first step, you can also try to redirect error messages to a file (see the menu in DNA) and post the contents of the resulting text file here for further examination.

**Comment by raulgtzmeave** [comment]
Hi! 

Thank you very much for your help. 

I already solved the issue. What I did was to create a new DNA database and then imported all the information from my old dataset. That seemed to work, so now I'm working on the new dataset and didn't lose any information.

Thanks!
