### ISSUE TITLE
Attribute manager: add/delete/rename/recode attribute variables

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#208]
Add functions to the attribute manager to add, delete, rename, and possibly recode attribute variables.

**Comment by Laurencebl1** [comment]
Hello, 

The rename function is also interesting to have. For example, when you want to rename a concept or merge actors, organizations or concepts together. 

Thanks

**Comment by leifeld** [comment]
> Hello,
> 
> The rename function is also interesting to have. For example, when you want to rename a concept or merge actors, organizations or concepts together.
> 
> Thanks

In commit 2f20e8124658873eebac708be89e76ee2ff38ac7, I added a statement editor for multiple statements. You can select the statements you want to recode in the statement table or right-click and "select all", with or without using the statement filter, and then right-click on the table and click on "edit statements" in the context menu. The statement editor allows you to copy the concept or actor (or coder) from one statement to all statements that are being edited. There is a table preview, where red cells indicate that a value is being changed. Once ready, you can save the results.

The statement type editor in the Statements menu now also allows you to add new attribute variable for the concepts, actors etc, in addition to the default ones (type, alias, note). You can also rename or delete existing ones. This was added in commits ca294b8ea0f80970ccf76a15897179e3d4a35bd4 and c6220447a62bcba7dc25cc881d5b8aab1890e4b8.

New versions of DNA 3.0 are now constantly being built and uploaded to GitHub automatically using the Gradle build system. See the README file on the main page for details on how to access the new JAR file after each commit. Note that you may need Adopt JDK 11 for this (8 may or may not be sufficient, not sure).
