### ISSUE TITLE
Add regex highlighter back in to DNA 3.0

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#211]
Add regex highlighter to DNA 3.0 GUI.

**Comment by Laurencebl1** [comment]
Hello, 
I work with the software and I find that the regex highlighter is really necessary for me. I have several texts that are not relevant and it is really easier for me to spot them with this tool. Also, even for the texts that are relevant, they can be very long so by seeing the words that I have chosen in color, I can focus only on the part that is interesting to me.  For the moment, I am working with both software (2 and 3) to have access to this tool. 

Thank you
