### ISSUE TITLE
Can't save errors in XML or JSON 

### ISSUE THREAD

**Issue by Laurencebl1** [leifeld/dna#224]
I am not able to record the errors in both possible formats (XML or JSON). I can click on both options but then the "save" button is greyed out so I cannot save. 

<img width="1360" alt="Errors1" src="https://user-images.githubusercontent.com/99191778/153158777-f278d968-a859-4cb0-8ecf-4efc1d9796ee.png">

I am on DNA 3.0.0 , macOS Monteray, Java version is Temurin-16.0.2+7

**Comment by leifeld** [comment]
Fixed in commit 055e17d4ac77a8e22efd89f1952a3a80705d2eed.
