### ISSUE TITLE
Research in filter

### ISSUE THREAD

**Issue by Laurencebl1** [leifeld/dna#227]
Hi, 
There is a bug in the «filter» section when i try to do a research. I got you a video and the text in my terminal. 

I can't do any research. I don't think it's because the function doesn't work at all, but it's the display. So it's hard for me to type in a name or an organization and do a search. 

DNA 3.0.1 + MacOS Monteray + Java version Temurin-16.0.2+7

![5B0354D0-13A8-42AA-A79F-BD1091D7A2D2_1_102_o](https://user-images.githubusercontent.com/99191778/153760795-0f9a1ae6-37f1-41f6-8743-7ce83848d7b8.jpeg)

[Résultat de Terminal12.pdf](https://github.com/leifeld/dna/files/8055952/Resultat.de.Terminal12.pdf)

**Comment by Laurencebl1** [comment]
I think my video is not working. Anyway, when I write, I can't really see the letters and it writes to the left and not the right. So my words are written in the wrong direction. I can't see my word. I have to underline it if I want to see it. Then it's hard to erase. It doesn't really work. I have to click in another box and then go back to the word to delete one letter at a time. 

I will try to send you the video on slack because I think my description is not really the best. 

Thank you 
<img width="331" alt="1" src="https://user-images.githubusercontent.com/99191778/153761187-decd0da7-b5af-4072-ae48-58505b84c380.png">
<img width="331" alt="2" src="https://user-images.githubusercontent.com/99191778/153761195-646690a0-4a12-4a0d-a861-d04793a41f75.png">

**Comment by leifeld** [comment]
I recently fixed some problems with the filter function, but I don't remember if that was before or after you obtained the latest version. I will ask @TimHenrichsen to send you an updated version (DNA 3.0.2). Would be great if you could try it again with that version and confirm if the problem is still there. Thanks.

**Comment by Laurencebl1** [comment]
I just download the DNA 3.0.2 and the problem is solve. Thank you
