### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Laurencebl1** [leifeld/dna#231]
Hello, 

I don't know how to describe what is happening with DNA. I have the impression that it is related to the research section of statements. I will attach the reports. 
When the problem occurs, I have to quit my DNA and open it again. 

MacOS Monteray, DNA 3.0.2, Java Temurin 16.0.2 +7

[DNA BUG 25Feb.pdf](https://github.com/leifeld/dna/files/8144611/DNA.BUG.25Feb.pdf)
[Philip 15.02.2022.pdf](https://github.com/leifeld/dna/files/8144632/Philip.15.02.2022.pdf)
[Tim 17feb2022.pdf](https://github.com/leifeld/dna/files/8144634/Tim.17feb2022.pdf)

**Comment by leifeld** [comment]
What do you mean by "research section of statements"? What are the symptoms in DNA? Under what circumstances does the problem occur?

**Comment by Laurencebl1** [comment]
the right section in the DNA when you want to do a research to find an organization, a person or other things. I think it's happen when i click on "current" and after on "filter". I will send you a picture. The section where you can choose between statements and annotation doesn't appear and i can't write some thing in the research section. I can do statement but if I refresh the window will just stay in the starting mode. (Sorry it's not really a good description of what is happening). I will send you a picture of that too. I will join an other report here

**Comment by Laurencebl1** [comment]
I'm not able to join pictures here so I send them to you in Slack.

**Comment by leifeld** [comment]
Thanks for the description.

It should be possible to include PNG screenshots here.

Does this happen every time you click on "current" and then "filter"? If not, what has to happen to trigger the problem?

**Comment by Laurencebl1** [comment]
I think it happens most of the time when i do that. I will work with DNA today, so i will check it.
<img width="1470" alt="25feb- when refresh" src="https://user-images.githubusercontent.com/99191778/155954911-9b4b9809-2e5e-4c36-82db-02034bb9190e.png">
<img width="378" alt="25feb-filter" src="https://user-images.githubusercontent.com/99191778/155954924-afb698bd-4aee-47cc-8c21-11a04a67b2c3.png">
[25feb-researchbug.pdf](https://github.com/leifeld/dna/files/8151930/25feb-researchbug.pdf)
[DNA BUG 25Feb.pdf](https://github.com/leifeld/dna/files/8151933/DNA.BUG.25Feb.pdf)
[Philip 15.02.2022.pdf](https://github.com/leifeld/dna/files/8151941/Philip.15.02.2022.pdf)
[Tim 17feb2022.pdf](https://github.com/leifeld/dna/files/8151942/Tim.17feb2022.pdf)

**Comment by leifeld** [comment]
Thanks. I'll look into it ASAP, but I won't get to it today because of teaching obligations.

**Comment by Laurencebl1** [comment]
No problem. I will join an other PDF files. The problem occurred today as well, but compared to the other times, I had been working with the tab on the right for about 1h30 when the error occurred. Maybe this can help.

[2 march 2022 (Researchbug).pdf](https://github.com/leifeld/dna/files/8170848/2.march.2022.Researchbug.pdf)

**Comment by Laurencebl1** [comment]
Hi Philip ! I just want to know if something have been found about the situation. I need to clean up the statements that are in some concepts, but I can't do that until this problem is solved since I always have to close my software if I do a concept search and then go to a particular document. I'm still coding in the meantime but I'd like to move this part forward soon. I'm attaching a new report here, if that helps. 

Thanks a lot 
Laurence
[March 10 2022.pdf](https://github.com/leifeld/dna/files/8224270/March.10.2022.pdf)

**Comment by Laurencebl1** [comment]
Me again. I feel like the problem comes when I create a new concept. I mean, I go between Filter and Current correctly but when I create a new statement, the error message appears at the bottom of my screen and DNA stops working. The errors accumulate if I try to do something and if I refresh, the documents don't reappear and the page stays blank. 
I don't know if this is related.

**Comment by leifeld** [comment]
I think I have been able to fix the problem. I will send a new test version by email in a few minutes. The last few details about when this happens (after creating a new statement and then opening the statement filter) were very helpful in identifying the problem. Thanks again.

I have gone through the error messages you sent, and there appear to be two different problems, though: one with the statement filter (which has been fixed) and another one in the attribute manager with the way the table is displayed. Some of the error logs contain the following entry:

> java.lang.NullPointerException: Cannot invoke &quot;javax.swing.table.TableCellRenderer.getTableCellRendererComponent(javax.swing.JTable, Object, boolean, boolean, int, int)&quot; because &quot;renderer&quot; is null

Pointing to the following lines in the code:

> java.awt.Component.setVisible(Component.java:1667)
> at java.desktop/java.awt.Window.setVisible(Window.java:1032)
> at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)
> at gui.AttributeManager.&lt;init&gt;
> (AttributeManager.java:305)
> at gui.MainWindow$ActionAttributeManager.actionPerformed(MainWindow.java: 2313)
> at java.desktop/
> javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> at java.desktop/

I have looked at the attribute manager again but couldn't find anything that may have caused the error. If you do come across it, please do open a new issue with a description of how to find the problem. Thanks.

Tagging @TimHenrichsen because some of the attribute manager error logs came from him apparently.
