### ISSUE TITLE
Existing Database won't open

### ISSUE THREAD

**Issue by luciekoenig** [leifeld/dna#233]
Hello DNA-Community!
I have been working with DNA for my master thesis, but today for some reason it wasn't adding any new statements, so I restarted my computer and when I tried to open the database in DNA, it just wouldn't open anymore. 
I can still open databases from older projects and I tried it on different computers as well, so it seems to be a problem with the database itself, not the software.
Any idea what I could do now? I was pretty far along, so I pray my work isn't all lost and I hope it can be fixed. 
Any thoughts and tipps would be really appreciated!
Thanks in advance!

**Comment by leifeld** [comment]
If you can send an email to me, I'm happy to take a look at the database and get back to you here.

Just a few questions: which DNA version are you using? What is your operating system? Was there anything specific you did before the problem occurred that could give me a hint about what may have caused the problem? Have you been storing the database in a synchronised folder, such as Dropbox? Have you used very long documents?

**Comment by luciekoenig** [comment]
Dear Professor Leifeld,

thank you so much for your very quick reply to my DNA issue on GitHub! I am
happy to send you my database in question attached to this e-mail.

To answer your questions:
I am using the DNA2.0 beta 25 on MacOS.
Several programmes on my computer were acting up a bit today and when I
tried to code a statement within a document in the database, it wasn't
adding the new statements, so I closed all applications on my computer and
restarted it. After that I just wasn't able to open this database.
When I open it with TextFiles, it shows me all documents up until the very
last one I was working on. So I am hopeful the data is there, I just don't
know how to get it to open again in DNA.
I have been storing the database on my desktop, but not in a synchronised
folder, such as Dropbox.
The documents I used are usually between 2-4 pages long and I had almost
200 of them and about 1200 statements.

I hope that helps! Thank you so much for looking into it! I really
appreciate it.

Kind regards,
Lucie Koenig

Am So., 13. März 2022 um 00:27 Uhr schrieb Philip Leifeld <
***@***.***>:

**Comment by leifeld** [comment]
I have fixed the problem and will send you the database back by email in a few minutes.

It appears that you recently deleted a document (ID 184), but for some reason the statements contained in the document (statement IDs 1294-1299, person = Samoa) were not deleted. Perhaps there was some file access issue on your computer while the operation was saved to disk. It's hard to tell. I have deleted those six statements and could open the database again after doing so. Please make sure you add this document and the statements again if needed.

I am currently working on DNA 3.0. The new version will take measures against problems like these. In particular, whenever something is deleted or added, the operation is first submitted to the database until it is complete, and only then the change is committed. This effectively prevents deletion operations from being interrupted like in your case. I am going to release the new version this summer.

**Comment by luciekoenig** [comment]
Dear Professor Leifeld,

thanks a million for your immediate help! I really appreciate it so much.
I was able to open the database and re-added the document and it all works fine again now. 
Beyond happy the database was not lost!

Excited for the new DNA 3.0 release this summer.

All the best wishes!

**Comment by leifeld** [comment]
Glad this worked out. You are welcome.
