### ISSUE TITLE
Disable editing in value column (attribute manager)?

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#234]
Right now, you can edit entries in the “Value” column in the attribute manager. Would it make sense to disable this possibility and let users recode values only in the statement recoder? Or do you want to enable users to have both possibilities to recode values?

**Comment by leifeld** [comment]
This is an intended recode function because the statement recoder does not rename entity values. It provides complementary functionality by also recoding the corresponding statements.
