### ISSUE TITLE
Cannot connect to MySQL

### ISSUE THREAD

**Issue by alamsyah78** [leifeld/dna#241]
Dear all,

I cannot connect to MySQL. Here, is the log:

logger stack trance: logger.LogEvent
exception stack trace: java.lang.NullPointerException: Cannot invoke "javax.sql.DataSource.getConnection()" because the return value of "sql.Sql.getDataSource()" is null at sql.Sql.getVersion(Sql.java:4139)

Software: DNA 3.0
Java: 18.0.1.1 2022-04-22
Mac: macOS Big Sur version 11.6.6

Thanks to read this message.

Regards,

**Comment by alamsyah78** [comment]
I solve this problem.

**Comment by leifeld** [comment]
Sorry for not responding sooner as I was travelling. May I ask, why did this error occur, and how did you solve it? Thanks.

**Comment by alamsyah78** [comment]
This error occurs because I do not input several MySQL parameters correctly. I tried several times until the connection was established. Thank you for your response, Prof. Leifeld! 

Best regards from Indonesia.

**Comment by leifeld** [comment]
Thanks. I'll see if I can create a more useful error log message if I am able to reproduce the problem.
