### ISSUE TITLE
Open DNA Connection Profile

### ISSUE THREAD

**Issue by alamsyah78** [leifeld/dna#242]
I create a DNA connection profile using DNA 3.0 and use it in R Studio. I get this message:
#
Error in .jcall(dnaEnvironment[["dna"]]$headlessDna, "Z", "openConnectionProfile",  : 
  RcallMethod: invalid object parameter

Thanks for the attention.

**Comment by leifeld** [comment]
Thanks for reporting this. I'll investigate, but it may take a few days before I get to it. Just to rule this out: did you successfully call `dna_init()` before opening the connection profile?

**Comment by alamsyah78** [comment]
Q: Did you successfully call dna_init() before opening the connection profile?
A: No, because I get an error when initializing dna_init() (see attachment)
<img width="689" alt="dna error report" src="https://user-images.githubusercontent.com/16342588/177049889-330a01c8-7ef6-4c10-9b9e-46b478de564b.png">
.

**Comment by leifeld** [comment]
Thanks, that's helpful. Note to myself: I think I may need to remove `java.awt.*` imports from the Java source file `rDNA` references for this to work. I should also add more sensible error message to all functions in `rDNA` if `dna_init()` was not successfully executed before using the respective function that depends on it.

**Comment by leifeld** [comment]
Sorry it took me so long, but this has been fixed now (in commit 1906b0cffe338f6ea95fb7aa6d63f0db2f318c5a) and will be included in DNA 3.0.11 upon release, which is planned for this month. See also #270 for more details.
