### ISSUE TITLE
could not find function "dna_gui"

### ISSUE THREAD

**Issue by april9715** [leifeld/dna#249]
When I want to test if rDNA can be loaded into R Studio correctly, I get this message:
![image](https://user-images.githubusercontent.com/114382651/192205307-219b65e9-26e5-4a50-8df0-5218b3d88017.png)

**Comment by leifeld** [comment]
The 3.0.8 version doesn't have the functionality of the previous rDNA version yet. See the [solutions posted here](https://github.com/leifeld/dna/issues/247).

**Comment by april9715** [comment]
> Thank you so much for the fast response.
