### ISSUE TITLE
In-text search function for DNA3

### ISSUE THREAD

**Issue by SofieRoehrig** [leifeld/dna#252]
It would be amazing if you could prioritise to bring back an in-text search function for DNA3 :)

**Comment by leifeld** [comment]
There is a full-text search function in the Documents menu, which searches across all documents in the database. I have just added a check box to filter the search results by the documents that are currently selected in the main window to permit within-document searching. The search function can also be accessed quickly from the main window using the keyboard short-cut <kbd>CTRL</kbd>+<kbd>F</kbd> if a database is open. Can you test this functionality and let me know if this works as intended? I have uploaded a trial version for you here: [DNA.zip](https://github.com/leifeld/dna/files/10232586/DNA.zip).

**Comment by SofieRoehrig** [comment]
Great, we just tested it and it works! :)
