### ISSUE TITLE
Unable to choose location of new database in DNA - prevents access to work

### ISSUE THREAD

**Issue by KaiSteemers** [leifeld/dna#267]
Using Mac (M1, 2020)

When trying to create new DNA database there is no ability to choose the location of database, not able to click OK. (image 1)

When no location of database is chosen data structures are set up in private/var folders which is inaccessible. (image 2)

<img width="1372" alt="Screenshot 2023-02-21 at 18 12 32" src="https://user-images.githubusercontent.com/126009010/220427479-1cf57a1c-4451-459f-9d09-5f5e981132ad.png">

<img width="1366" alt="Screenshot 2023-02-21 at 18 13 40" src="https://user-images.githubusercontent.com/126009010/220427498-a3f548e9-cc13-4751-bbb3-66d5c02d8cc7.png">

Feel like I'm missing something really obvious maybe? Have taken advice of previous issue raisers with regard to Pictures folder. Didn't have this problem with pre-existing sample files downloaded to practice on.

Thanks

**Comment by leifeld** [comment]
Thanks for reporting this. Looks like the same Mac Java security issue that plagued previous Mac users. I'll try to look into it by the end of the week.

One thing you could try in the meantime is to open a terminal and type `java -jar dna-3.0.9.jar` from the directory where the DNA JAR file is stored. There is a possibility that this gives DNA proper user rights. Can you try and report back? Thanks.

**Comment by KaiSteemers** [comment]
> Thanks for reporting this. Looks like the same Mac Java security issue that plagued previous Mac users. I'll try to look into it by the end of the week.
> 
> One thing you could try in the meantime is to open a terminal and type `java -jar dna-3.0.9.jar` from the directory where the DNA JAR file is stored. There is a possibility that this gives DNA proper user rights. Can you try and report back? Thanks.

As so?:
<img width="510" alt="Screenshot 2023-02-21 at 18 44 38" src="https://user-images.githubusercontent.com/126009010/220432189-35e5e4be-b60a-435b-ad10-07691090c456.png">

**Comment by leifeld** [comment]
Just, but either the JAR file needs to be in the home directory, or you need to navigate to the directory where the JAR file is located using the `cd` command on the terminal.

**Comment by leifeld** [comment]
You can display the files that are currently present using `ls`.

**Comment by KaiSteemers** [comment]
I have moved dna-3.0.9.jar from my desktop to the home directory

it now displays this:

<img width="575" alt="Screenshot 2023-02-21 at 19 05 02" src="https://user-images.githubusercontent.com/126009010/220436199-5899ffb3-b499-4f61-8f1f-0ec6b326b567.png">

**Comment by KaiSteemers** [comment]
and opens the discourse network analyzer

**Comment by leifeld** [comment]
Great. And does opening DNA in this way fix the problem you reported above (as a work-around until I get to fix it properly)?

**Comment by KaiSteemers** [comment]
Unfortunately not. I am still not able to click 'ok'

<img width="1370" alt="Screenshot 2023-02-21 at 20 42 16" src="https://user-images.githubusercontent.com/126009010/220454049-47daad49-b5ba-4e27-b752-954d41a295f0.png">

**Comment by KaiSteemers** [comment]
thank you, I really appreciate it!

**Comment by leifeld** [comment]
Probably unrelated, but perhaps worthwhile to check out: #201.

**Comment by leifeld** [comment]
Hi again. Can you please check out [this temporary version](https://www.dropbox.com/s/k439y68p9znznzr/dna-3.0.10.e1.jar?dl=0) and report back if it fixes the problem? I will include it in the next release, probably next month, but it should be OK to work with it until then. The changes can be reviewed [here](60c06615362cf1a552be8c0b314923536d3f9011).

**Comment by KaiSteemers** [comment]
Hi, 

I just used it and it worked!

Thank you very much.

**Comment by leifeld** [comment]
Excellent! Thanks for your patience and testing it. Will close the issue now.
