### ISSUE TITLE
Can't browse Local SQLite file

### ISSUE THREAD

**Issue by Xiaoyu-Zh** [leifeld/dna#268]
My system is MacOS and I just downed the DNA3.0, JDK17.0.6+10 for MacOS aarch64, and sample data following the introduction video.  

I saved sample data on the desktop.  When I try to connect the sample database, I click "browse", however, the desktop folders are empty, and all other folders (e.g., downloads folder) show empty as well.

It would be highly appreciated if someone can help me with a solution.

**Comment by leifeld** [comment]
I have recently fixed this MacOS issue. See #267, where a temporary version including the fix is available. It will be distributed more widely in the next release as well. I'll close this issue as fixed for now, but please reopen if this doesn't solve your problem. Thanks.

**Comment by Xiaoyu-Zh** [comment]
It works!! Thanks so much for your immediate reply.
