### ISSUE TITLE
When re-opening DNA files with Visone, labels of codes are no longer visible

### ISSUE THREAD

**Issue by KaiSteemers** [leifeld/dna#271]
This seems to only be a problem when I am returning to networks I have previously generated as opposed to newly generated networks.

However, where codes have previously shown they no longer do.

The data is still there as when I open the attribute manager it shows me the node attributes etc.

Any reason why this may be happening and how to resolve?

Using Mac.

<img width="1419" alt="Screenshot 2023-03-27 at 16 39 38" src="https://user-images.githubusercontent.com/126009010/227991925-6a6f6a0d-0ec3-4822-a77b-f8b1f8eb51bc.png">

**Comment by leifeld** [comment]
Seems to be a glitch in visone. I have experienced this as well after certain analyses in visone, including community detection. You should be able to get the labels back by clicking on the `visualization` tab on the left, then `mapping`, `labels`, `node labels`, and selecting the variable with the names, then proceeding.

**Comment by leifeld** [comment]
I'll close this, assuming this answered your question. If not, please feel free to re-open the issue or create a new one.
