### ISSUE TITLE
empty csv file after exporting database 

### ISSUE THREAD

**Issue by Bignia** [leifeld/dna#273]
Dear all
Dear Dr. Leifeld 

Unfortunately, after exporting my database from the dna program to a csv file, it was empty. what is the reason for this? 

and when i tried to access my database in the dna program again, it was also empty.

I would be very grateful for your help!

Kind regards
Bignia Luetscher

**Comment by leifeld** [comment]
Which DNA version did you use?

If 3.0, was there any error or warning?

You can open the dna database in SQLiteBrowser to see if any data are contained in the database.

Did you save your database in a Dropbox folder or similar? Could it have been overwritten in any other way?

Empty CSV file sounds like an empty database.

**Comment by Bignia** [comment]
Thank you for your fast reply.

I use 3.0.11 and there was no warning only error messages, which says (SQL) failed to retrieve coders from database.

and I can‘t open it as it seems that the database is empty, similar to the csv file.

sadly I only saved the database in the dna program itself… is there any way I can get my database back? it is for me thesis and contains over 1500 statements.

Thank you in advance for your response

**Comment by leifeld** [comment]
Coders cannot be retrieved if the database is empty, i.e., if no coders were stored in the database.

Did you save your database in a Dropbox folder or similar? Could it have been overwritten in any other way?

I'm happy to take a look at the database if you send it to my email address or post it here, but it does sound like it might be empty.

**Comment by Bignia** [comment]
_Coders cannot be retrieved if the database is empty, i.e., if no coders were stored in the database._
The strange thing is that a saved a profile as a coder even with a password and I saved the database sadly only in the program on my laptop as I thought it would save my database automatically in the program odr in the coder profile itself.

I would be really glad if you could take a look at my database, I will send it to you by email.

Thank you a lot in advance!

**Comment by Bignia** [comment]
Dear Mr. Leifeld,

Enclosed I am sending you my database and the csv file as already mentioned in my comment on GitHub.

Kind Regards,

Bignia Lütscher


Von: Philip ***@***.***>
Gesendet: Freitag, 7. April 2023 17:50
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [leifeld/dna] empty csv file after exporting database (Issue #273)


Coders cannot be retrieved if the database is empty, i.e., if no coders were stored in the database.

Did you save your database in a Dropbox folder or similar? Could it have been overwritten in any other way?

I'm happy to take a look at the database if you send it to my email address or post it here, but it does sound like it might be empty.

**Comment by leifeld** [comment]
The database didn't get through because you replied to the GitHub notification. Please send the database directly to my personal email address, which you can find [here](https://www.philipleifeld.com/contact/).

Yes, any changes should be saved automatically into the database, whether you use a connection profile or open the database directly. Connection profiles act as bookmarks. They don't contain any data themselves. They merely point DNA to the location of the database, similar to a bookmark in a browser. So, if you moved the `.dna` database file to a different location on your computer, the connection profile may no longer find the database when you try to open it. Could this be the source of the frustration? Do you know where the `.dna` file is located? If so, can you open it instead of opening the connection profile?

**Comment by leifeld** [comment]
I have received your database by email. Thanks. It contains two empty documents without text or title, no statements, and no other data.

Can you provide any details on what steps you have taken?

- Did you save the database in a regular subdirectory in the user directory on your hard disk? Or in a cloud directory that gets overwritten occasionally, such as Dropbox, Box, Google Drive, Onedrive etc?
- Did you select any statements and/or documents and delete them in DNA?
- Did you move or rename the database file on your hard drive at any point?
- I noticed that your database file was called `BA Neuer Datensatz.dna`. Is there also an old database? Does it contain any of the data?
- Are you sure you inserted the documents and added the statements in precisely this database, or is it possible that you have another DNA database file saved somewhere that contains the data? Perhaps with an identical file name, saved in a different location?
- Any other useful information on what steps you have taken and in what order? It is difficult to see what may have happened without any other details.

**Comment by Bignia** [comment]
perfect, and yes this two database where the result of my export of my database and the only thing I found on my hard disk on my computer.

 so my steps where the following:

1.  I made a coder account and in this database I saved all my statements.

2. this database was saved on my hard disk in a folder (not in a cloud or something similar)

3. when I finished my work ( after around 2 weeks) I wanted to export the database, so I clicked on exporting in the dna program. After that it appeared automatically a csv document in the same file as my .dna was saved but empty (as I sent you  in the previous mail).

4. then I tried to open the database again to do the export again, but it didn‘t worked, because I couldnt log in.

5. then I tried to open a new database with a new password to import the „old“ database (thats why I have sent you also the database BA neuer Datensatz). And then I realized that the „old“ database was empty.

And I also didnt saved my data in a other file on my computer obly in the dna program itself and in this file I mentioned before.

I hope this information helps you and thank you again to take your time to face my issue.



Am 08.04.2023 um 22:23 schrieb Philip Leifeld ***@***.***>:

﻿

I have received your database by email. Thanks. It contains two empty documents without text or title, no statements, and no other data.

Can you provide any details on what steps you have taken?

  *   Did you save the database in a regular subdirectory in the user directory on your hard disk? Or in a cloud directory that gets overwritten occasionally, such as Dropbox, Box, Google Drive, Onedrive etc?
  *   Did you select any statements and/or documents and delete them in DNA?
  *   Did you move or rename the database file on your hard drive at any point?
  *   I noticed that your database file was called BA Neuer Datensatz.dna. Is there also an old database? Does it contain any of the data?
  *   Are you sure you inserted the documents and added the statements in precisely this database, or is it possible that you have another DNA database file saved somewhere that contains the data? Perhaps with an identical file name, saved in a different location?
  *   Any other useful information on what steps you have taken and in what order? It is difficult to see what may have happened without any other details.

**Comment by leifeld** [comment]
Is it possible that you exported a CSV file and chose the DNA database as a destination file, thereby overwriting the database?

You wrote that you created the empty database `BA neuer Datensatz.dna` after unsuccessfully exporting from an old database. This new, empty database is the file you sent me. But I haven't seen the old database yet. Can you send it to me by email for inspection?

**Comment by Bignia** [comment]
yes that could be, because I choose in the exporting pop-up window that I wanted a csv document… but did you know why at the end both of the database (the csv one and the .dna one) were empty? did I deleted the data? or were is it now?

yes, the old one is also empty, at the moment I am not at home but I will send it to you as soon as I am at home again.

Kind regards

Bignia Lütscher


Am 09.04.2023 um 01:14 schrieb Philip Leifeld ***@***.***>:

﻿

Is it possible that you exported a CSV file and chose the DNA database as a destination file, thereby overwriting the database?

You wrote that you created the empty database BA neuer Datensatz.dna after unsuccessfully exporting from an old database. This new, empty database is the file you sent me. But I haven't seen the old database yet. Can you send it to me by email for inspection?

**Comment by leifeld** [comment]
As you reported by email that you found all your data in the old database on your computer, I will close this issue here. I'm glad you did not suffer any data loss! Good luck with your analysis!
