### ISSUE TITLE
Statistics of our DNA?

### ISSUE THREAD

**Issue by ShitamSapud** [leifeld/dna#277]
Hello guys,

I am trying to understand how I can explore statistically my network? Specifically, I am having more or less three cluster/communities and I would like to explore what are their.. opinions pattern if that make sense. For instance, community 1 tends to rather disagree with policy 1 but not with policy 2 meanwhile community 2 tends to support policy 2 but not policy, etc.. Because right now I have three cluster but I do not know how to interpret them.

 Is R the only way?

Any help would be much appreciated !

Kindly

**Comment by leifeld** [comment]
Several things you could do to understand the concept profile of the nodes in a specific cluster:

* Export a two-mode network of actors and concepts, for example to visone, and zoom in to trace which concepts the actors within a coalition have in common (with the same agreement pattern).
* Look up what these actors stand for in DNA using the statement filter below the statement table. Look specifically at their statements to understand where these conflicts are coming from. You can also look up actor-concept combinations from the two-mode network in the statement filter to understand the context in which two actors agreed or disagreed on a concept.
* Use a heat map in R to see in a single diagram how actor clusters and belief clusters go together.

**Comment by ShitamSapud** [comment]
Hey Leifeld, thank you for your fast and helpful reply, as usual.

It is suprising that there is no easier way to look at statistic to define more rapidly and accurately the profiles of existing clusters. Each of my cluster have more than 100 nodes with roughly 40 different policy beliefs, so it's quite hard to look at them one by one...

I will give it a try with R, if you have any other suggestions, I would be very grateful !

Than you again:)

**Comment by leifeld** [comment]
For exploratory purposes, visone usually works pretty well. In R, you can't zoom into the network diagrams very well.

I've been working on some methods for describing discourse networks better. I'm in the process of submitting some of this work to journals. But if you can think of specific methods to summarise clusters, please let me know, and I'll consider them!
