### ISSUE TITLE
Attributor Management Issue

### ISSUE THREAD

**Issue by Xiaoyu-Zh** [leifeld/dna#282]
There are two concept attributor that i no longer used for coding. But i couldn't delete them. I checked the corresponding entity 24,35, they are actually assigned to other concepts. I also try to use the filter function to find the entity that is assigned to the "error1", "error2" concepts, but there is no entity assigned to those concepts. Even though, i couldn't delete this two concept attributor. 

<img width="941" alt="WeChat16432f3d7879deab0ab05224f9f0905b" src="https://github.com/leifeld/dna/assets/126673187/124a29c3-836b-47d4-96f4-9114c8700230">

<img width="1287" alt="image" src="https://github.com/leifeld/dna/assets/126673187/c5aa485f-c5e5-4e5b-acc6-2f76355021c5">

**Comment by leifeld** [comment]
In the screenshot, it looks like you are not trying to delete them but rather rename/recode the attributes. You can only delete them if there are no statements that use them. Have you tried the statement filter in the main window to find the statements they are in and delete the respective statements first? After that, they should appear in red in the attribute manager, and you should be able to delete them. I am not sure how you produced the error message, but we will first have to sort out this issue before we can tackle the error message. You can also feel free to join the DNA Matrix space for real-time discussion if that's easier. See the GiHub project landing page under "Documentation and Community" for details.

**Comment by Xiaoyu-Zh** [comment]
> yes, i try to use the filter function to find the statement. But there is no statement attached to these concepts. That is why I'm confused.

**Comment by Xiaoyu-Zh** [comment]
Thanks for your immediate reply!! The issue is solved when I reconnect the database.

**Comment by leifeld** [comment]
Thanks, that's good to know. Maybe changes made in the attribute manager (renaming of entities) don't trigger an automatic refresh of the data in the statement table. I need to look into this. I'll close this for now, but feel free to re-open if the problem hasn't been solved for you.
