### ISSUE TITLE
Inquiry about Temporal Network Autocorrelation Models

### ISSUE THREAD

**Issue by LuoRui76** [leifeld/dna#287]
Dear Professor Philip Leifeld,

I hope this email finds you well. I am reaching out to you today because I have been working on my doctoral thesis, which involves the use of temporal network autocorrelation models.

While conducting my research, I came across your work in developing the xergm package, which previously contained functions for temporal network autocorrelation models. However, it seems that these functions are no longer available or functional. I am writing to inquire if you could kindly provide guidance on which package or functions are currently suitable for implementing temporal network autocorrelation models.

**Comment by leifeld** [comment]
See the following [archival notice in the tnam repository](https://github.com/leifeld/tnam#archival-notice):

> The package uses maximum pseudolikelihood for estimation, which is likely biased. Consider using the multiparametric spatio-temporal autoregressive (M-STAR) model instead if you have temporal data. If you have a cross-sectional dataset, consider using the BANAM package. The tnam package is archived until better estimation routines have been implemented, but there are currently no plans for this.

You can still download the tnam package from the [CRAN archive](https://cran.r-project.org/src/contrib/Archive/tnam/), but there is no more support available.
