### ISSUE TITLE
filtering concepts 

### ISSUE THREAD

**Issue by Nousnous24** [leifeld/dna#290]
Dear Sir/ madam, 
 
To analyze my data in DNA, I would like to filter upon one concept to see what all my organisations have said about it in order to explain the figure I made with visone. Unfortunately, when I try to filter on concept in the panel on the right side, the things I type will search the text in the document instead of the concept that I would like to filter. This prevents me from seeing all the statements that have been made about concept x in one tabel. 

I hope you could help me.

**Comment by leifeld** [comment]
Which DNA version is this? I have just tried it with the `sample.dna` file and DNA 3.0.10, and it seems to work fine. I entered `CO2 legislation`, and it showed the 10 statements corresponding to "CO2 legislation will not hurt the economy." in the statement table on the right. Can you check that you get a different result and report back?

**Comment by leifeld** [comment]
Closed because no response.
