### ISSUE TITLE
How to add additional attributes within DNA?

### ISSUE THREAD

**Issue by YihyunKang** [leifeld/dna#292]
Hello,

The update announcement says it is possible to add additional attributes to the actors, but I don't know how. 

I can only find alias, notes and types columns in the attribute manager. 
I installed the most recent version of DNA.

Best regards,
Yi hyun

**Comment by leifeld** [comment]
You should be able to edit the attributes of a variable in the statement type editor, I believe.

**Comment by YihyunKang** [comment]
Thank you very much! I found the function and it works now.

**Comment by leifeld** [comment]
Glad it worked and happy to help!
