### ISSUE TITLE
Closeness Value for Concept Network

### ISSUE THREAD

**Issue by izallukman** [leifeld/dna#293]
Hi Professor Leifeld,

I find that, the output of closeness value (%) from Visone for Concept Network is often more than 1. Meanwhile, the closeness value (%) in Actor Network and Person-Concept Network Affiliation is always decimal numbers between zero (0) and (1). Is this true?

Thank you 
Fahrizal

**Comment by izallukman** [comment]
Hi Professor Leifeld, 

I would like also to inquire about the problem in retrieving the coding database from DNA 2.0 version to DNA 3.0.X version ("failed to retrieve statement"). 
![image](https://github.com/leifeld/dna/assets/171114462/3c99baf8-f698-471f-9e7e-b82e7caf97ce)
Thank you

**Comment by leifeld** [comment]
Regarding closeness, this may be better asked on the [visone forum](https://groups.google.com/g/visone-users?pli=1).

Regarding the error, there are several possibilities:

1. Can you try again with the latest version?
2. Can you check if this is a DNA2 or DNA3 database? You can only open DNA3 databases with DNA 3 without errors, and you need to import the database into an empty DNA 3 database if your database is a DNA2 file.
3. It could also happen if the connection went away, for example if the file was moved or blocked, e.g., because the drive was removed or a cloud sync service was accessing it or something else.

Is the problem still there?

**Comment by izallukman** [comment]
Dear Professor Leifeld,

Thank you for getting back to me.
As you were just aware in the edited response, this is the error when I tried to open the DNA database into the DNA3 version. I will try the steps as you suggested.

In this message, I would like to inform you that related to the project I am doing at the moment is to support a data analysis research project for the Vice Minister of ICT in Indonesia. The team is planning to visit Europe at the end of August. Perhaps If you have time, the delegates may want to visit you for discussion.

Thank you

**Comment by leifeld** [comment]
Thanks. I'd be happy to meet up, but I am currently staying as a Mercator Fellow and guest professor at the Graduate School for Digital Platform Ecosystems at the University of Passau in Germany. I am not sure if you are planning to travel to the region. But if you do, please feel free to send an email to talk about details. I will be back in Manchester after 20 September 2024.

**Comment by izallukman** [comment]
Thank you Professor Leifeld for the response.

Professor Leifeld, in this message please allow me to introduce myself. I am Fahrizal L. Budiono, Ph.D (https://www.linkedin.com/in/fahrizallukman/). I obtained my PhD from the University of Wollongong, Australia, majoring in Information Systems in 2023. 

In addition, I would like to inform you that I am aware that the team is planning to visit Germany as well (Week of 26th August). In this regard, would you mind informing us where the email we may send? Or perhaps, would you advise us if there is a possibility that you would like sending an invitation to our VM and the delegates to visit your current campus in Germany?

Regarding the planning above, My team leader for this research project, Professor Riant Nugroho, would like to share his contact (+62818660131/riantnd@gmail.com).

Thank you,
Warm Regards,
Fahrizal L. Budiono, PhD
+6285691935730 / fahr004@kominfo.go.id, izal.lukman@gmail.com

**Comment by leifeld** [comment]
Thank you. If you could please send details to my email address listed [here](https://www.philipleifeld.com/contact/) from your official email address, then I am happy to discuss a visit with my current host institution.

**Comment by izallukman** [comment]
Thank you Prof Leifeld.

I will send from my official email 

Warm Regards

**Comment by leifeld** [comment]
Excellent, thank you.
