### ISSUE TITLE
DNA cannot be opened on macOS ("cannot verify that this app is free from malware")

### ISSUE THREAD

**Issue by Euro-sevic** [leifeld/dna#297]
"dna-3.0.11(1).jar” cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware. 

I am using macOS 14.6.1 on a MacBook Pro. My security is set to allowing downloaded applications from the App Store and identified developers. 

Does anyone else have this issue?

**Comment by leifeld** [comment]
Have you tried setting it to "Anywhere" as suggested [here](https://macpaw.com/how-to/fix-macos-cannot-verify-that-app-is-free-from-malware)?

**Comment by Euro-sevic** [comment]
Oh wow, I was wondering why I could not find an option to accept 'Anywhere' in my security settings. Turns out you need to disable it via the Terminal. Thank you, I have it now!
