### ISSUE TITLE
ImportHTMLWebpageTag: error messages for xml-elements

### ISSUE THREAD

**Issue by brandenberger** [leifeld/dna#48]
In ImportHTMLWebpageTag.java / ImportHTML.java / ImportWebpage.java add error messages if the chosen xml-elements cannot be found in the corresponding document/webpage. This could be similar to the warning message that was added in 2.0 alpha 8 for the date extraction. 

e.g.: 
try{
String title = file.select(titleElement).text();
}
catch(NullPointerException e) {
      String message = "\n Date not extractable.\nUse 'set date manually'-option."; 
      JOptionPane.showMessageDialog(new JFrame(), message, "Warning", JOptionPane.ERROR_MESSAGE);
}

**Comment by leifeld** [comment]
HTML import function was removed a while ago.
