### ISSUE TITLE
Add statement type editor

### ISSUE THREAD

**Issue by brandenberger** [leifeld/dna#51]
Add a rename-button for variables in the  Statement-Type-Edior.

**Comment by leifeld** [comment]
What about a small green "accept" button like the one right beside the statement type name on the left? When you click on it, the current variable is renamed?

**Comment by leifeld** [comment]
Statement type editor was removed a while ago and needs to be added back in.

**Comment by leifeld** [comment]
Implemented in [forthcoming version 3.0 of DNA](https://github.com/leifeld/dna#upcoming-release-of-dna-30).
