### ISSUE TITLE
Change agreement variable

### ISSUE THREAD

**Issue by brandenberger** [leifeld/dna#52]
Instead of one boolean that measures agreement (=1) and disagreement (=0), add ComboBox with three entries: 0 = disagreement, 1 = agreement and -1 is the initial value of the variable. If coder forgets to code agreement-variable it can be detected easily, as the variable would still be set to -1.

**Comment by leifeld** [comment]
Wouldn't this confuse people because they would interpret -1 to be a negative stance? What about having a null entry instead? Would that lead to filtering problems etc.?
