### ISSUE TITLE
Sometimes not possible to code new statement within another statement

### ISSUE THREAD

**Issue by QuintusSertorius** [leifeld/dna#55]
When I right click in order to code a number of selected words inside an existing statement as a new one, DNA sometimes selects the underlying already existing statement. This seems to be random and sometimes a statement can be coded after a number of tries, often not. Restarting the program does not help.

**Comment by leifeld** [comment]
Problem cannot be replicated. Please provide minimal self-contained example and/or detailed steps for reproducing the problem next time. Feel free to reopen this thread or a new issue with more details.
