### ISSUE TITLE
UI Issue: filter malfunction

### ISSUE THREAD

**Issue by QuintusSertorius** [leifeld/dna#56]
When using the filter set to 'current' in order to allow an easier overview over statements, I encountered an error where sometimes coded statements were not marked or the whole text was marked in red. Changing the filter setting back to 'all' and viewing another article reverted this; however, the list of statements showed only 2 coded statements afterwards.

**Comment by shrakulkarni** [comment]
Issue Fixed in version 2.0 beta 1
