### ISSUE TITLE
Lock documents while working on them

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#65]
## Current behavior
Every time a statement popup window is opened or closed or anything else is done, a database access takes place. This is slow and inefficient.

## Desired behavior
When a statement is opened or closed or a new statement is added or an existing statement is deleted, the changes should only be applied to the user interface and memory but not to the database. All changes are listed in a table in a new panel in the sidebar. There is a button at the bottom of this panel. Only when the user presses this button, all statement changes related to the document should be saved to the database. When the user accesses a different document, there should be a dialogue window that asks the user to save or discard the statement changes in the current document.

**Comment by shrakulkarni** [comment]
Instead of locking documents, it is good option to save the data related to a document or a sentence in a document at one go. Currently for every entity type connection is made and data changes are saved in DB. It is making application slow specially in the case of network/ online databases.

**Comment by shrakulkarni** [comment]
Solved by saving all the details of a statement at once while creating
