### ISSUE TITLE
Sort statements in sidebar by date, document ID, and position

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#82]
## Problem

The sidebar on the right contains the statement panel. The statement panel sorts all entries by statement ID. However, this is impractical in many settings because it does not necessarily correspond to the order of documents in the document table, and it would be more natural to navigate statements chronologically in the statement panel.

## Possible solutions
* One solution may be to add a small panel where the sort order can be set.
* Alternatively, this can be defined in the settings menu.
* Alternatively, the chronological sort order could be the default, but the table could be made sortable, and one could revert the sort order back to this default using a right click and selecting an entry from a context menu.

## Notes
* The statement table would have to be made sortable, with all implications, such as converting between model and view.

**Comment by StefanLindow** [comment]
what about length of the item? Many suggest to work a little bit on your research every day  , coders might find the time to code smaller texts instead of being forced to stop coding in the middle of a text; or they choose to code the biggest in suitable time slots.

**Comment by leifeld** [comment]
Implemented in DNA 3.0, which [will be released later this year](https://github.com/leifeld/dna#upcoming-release-of-dna-30). In DNA 3.0, the statement table can show various kinds of information as separate columns, and the columns are sortable.
