### ISSUE TITLE
Add function for saving and loading attributes to/from CSV

### ISSUE THREAD

**Issue by leifeld** [leifeld/dna#83]
In some settings, one would like to take an existing set of attributes (colors, types etc.) from one file and create a new file and prepopulate it with the existing attributes for easier coding. To do that, it would be helpful to have a function that allows the user to save attributes to CSV and load them back in. This would also facilitate editing the entries.

**Comment by ma19fr** [comment]
Hi Philip, are there any news about this issue?

**Comment by leifeld** [comment]
I have added a function `dna_getAttributes` to `rDNA`. This function retrieves a dataframe with the attributes from the file. I am planning to write another function `dna_setAttributes` to save any modified attributes back to the DNA file. This permits editing the entries easily by manipulating the dataframe in `R`. One could also save them to a CSV file, manipulate the CSV file, load it back into `R`, and then save them back to the DNA database using `dna_setAttributes`. Would this seem like a good plan?

**Comment by leifeld** [comment]
The `dna_getAttributes`, `dna_setAttributes`, `dna_addAttribute`, and `dna_removeAttribute` functions in rDNA offer this functionality now.

**Comment by simona-sz** [comment]
Hello. I have a question concerning these functions: I would like to define colors and types for 2 of my variables (Person and Topic) - how can I do that? I understood that in dna_setAttributes I can remove statements and in dna_addAttributes I can add attributes but not define a specific color for a specific value of my variable. When I apply dna_getAttributes I get a table with all attributes shown but they have no entries (or #00000) for colors - how do I get the entries in? (ID, Values and Frequencies are shown.)

You write: "This function retrieves a dataframe with the attributes from the file." Which file is that? Can I access it and define entries there?

 I use the rDNA 2.1.18 version, DNA 2.0-beta25.

I would be very greatful for an explanation! (Maybe this could be added to the manual?)

**Comment by leifeld** [comment]
There are a few functions for variable management. You could first get a table of variables from the database into R by using `dna_getVariables`, then manipulate the RGB color values you see there in the data frame, and finally put the variable definitions back into the database by using `dna_setVariables`. Other related functions are `dna_addVariable`, `dna_removeVariable`, `dna_renameVariable`, and `dna_recastVariable`.

It wasn't clear to me from your post if that's what you wanted or if you actually wanted to change the color of attributes/entities. If so, it's the same procedure but with `dna_getAttributes` and `dna_setAttributes` instead.

I think when I referred to "file", this was the database file.

**Comment by simona-sz** [comment]
Thank you for the quick reaction! I want to define colors for values in my variable "Thema", so that some topics appear in the Network-Graph as a green dot, and some as red dots (like in the manual on p.89 for the variable "organization"). 

When I apply dna_getAttributes I get the following table (I named "atP"):
![attributes Table](https://user-images.githubusercontent.com/109358897/191945237-0a7ab91c-0b4f-45c3-9a68-016b1c8fd2b8.PNG)

So I would like for example that the value "Baum" has the colour #1b9e77 instead of #000000.

Where I am stuck is how exactly to "manipulate the RGB color values you see there in the data frame, and finally put the variable definitions back into the database". I can see all the #0000 values in the column "color" - but what do I have to do to manipulate them? There is probably a simple step that is super logical to you but that I have no idea about ;) Do I somehow export the datatframe as csv and manipulate the vlaues there? or do I apply some if-function to assign colors? or...?

I hope I was clearer now.

**Comment by simona-sz** [comment]
I found a way to "manipulate" the values in the data frame: with "grepl()" accroding to this https://stackoverflow.com/questions/42075968/conditional-value-assignment-in-r

However I still do not understand, where the data file with the attributes is coming from. I imagined the DNA database would contain the variables that are used while coding. On p. 87 the manual suddenly talks about "the colors for the organization types saved in the database". But to me as beginner it is not clear where the information on colors and types is coming from and wehre it goes when I manipulate the dataframe. Wouldn't it be possible to introduce a short explanation of that in the manual? That is probably a minor issue but would help to understand, what one is working with.

Kind regards!

**Comment by leifeld** [comment]
You can see and manipulate the colors also directly in DNA, without R. If you click on the middle button of the three buttons in the upper right corner of the main window of DNA 2.0, a panel will open at the bottom. Switch to the right tab, which is the attribute manager. You can select the variable to edit and click on the colors to replace them. The manual should contain details about the attribute manager as well.

**Comment by simona-sz** [comment]
Thank you, that is my missing link! I managed to ignore that attribute manager completely during coding... I knew it must be something simple :)
