### ISSUE TITLE
2 different organizations

### ISSUE THREAD

**Issue by geeklight01** [leifeld/dna#90]
Hi, Is there a possibility to define that an actor making a statement belongs to 2 different organizations?

**Comment by leifeld** [comment]
Yes, in any given statement, you can combine a person with an arbitrary organization. This does not have to be consistent across statements. If necessary, click on the plus sign in the statement popup window to create a duplicate entry and change the organization in the duplicate. You can navigate those duplicates using the "current" filter in the statement panel in the sidebar on the right.

**Comment by leifeld** [comment]
Feel free to re-open this issue if there are follow-up questions.
