### ISSUE TITLE
export the statements to a CSV file

### ISSUE THREAD

**Issue by geeklight01** [leifeld/dna#91]
Hi! That would be great if there was an option enabling the export from the list of statements to a .csv file!
Maybe it s already possibl. If that should be the case, how?

**Comment by leifeld** [comment]
Yes, that is possible. I assume you are working with DNA 2.0? In that case, go to the network export function and choose "event list."

**Comment by geeklight01** [comment]
Yes exactly. Thanks, it works very well except that it does not recognize the special symbols. Is there a way to fix it?  For example in this word "Bâles" there's a special symbol on the "a", which is unfortunatley not correctly transferred in .CSV. That's a bit of a drawback when an other language than english is used.

**Comment by leifeld** [comment]
I just tested it on my computer, and it seems to work fine. Have you tried to open the CSV file in a text editor? There you should see that it's exported correctly. Are you trying to import the CSV file into Excel? In that case, you may need to specify the encoding of the input file during import, which is "65001 : Unicode (UTF-8)". If you do that, it should recognize those characters in the input file.

**Comment by geeklight01** [comment]
Works very well! Just tried with the text editor. Thanks
