### ISSUE TITLE
SQLite exception upon trying to load sample.dna

### ISSUE THREAD

**Issue by zafarimran** [leifeld/dna#98]
Hello,
I just installed DNA on my macbook (MacOS 10.8, Java version 1.8.0). Upon trying to load sample.dna, I could see the following exception in terminal:

java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)

Do I need to install SQLite as well? User manual doesn't specify any such thing. Why is the file not loading? I will appreciate any help I can get.

Best regards,
Zafar

**Comment by leifeld** [comment]
The `sample.dna` file was updated between DNA 1.31 and DNA 2.0 beta 19. The old version was based on an XML format while the new version is based on SQLite. You need to use the sample file that corresponds to the respective version. Did you try that? You may have downloaded the wrong version from the [Releases](https://github.com/leifeld/dna/releases) page.
