### ISSUE TITLE
Export - duplicates

### ISSUE THREAD

**Issue by stutti49** [leifeld/dna#99]
I work with dna 2.0 (beta 18).
When I export my database in. csv file and I precise in the DNA software that I want to overlook duplicate "across date range", only the statements which are unique appear in the .csv file. However I would like that statements which are duplicated in the DNA software appear in my .csv file only once instead of not at all (Without that I have to do it manually). 

If that is not possible how can I make sure that when I export my two-mode or one-mode network in Visone, there are no problems in regards to duplicates?

**Comment by leifeld** [comment]
> When I export my database in. csv file and I precise in the DNA software that I want to overlook duplicate "across date range", only the statements which are unique appear in the .csv file.

This is the expected behavior.

> However I would like that statements which are duplicated in the DNA software appear in my .csv file only once instead of not at all (Without that I have to do it manually).

I don't understand what you are trying to achieve. It's not true that they don't appear at all; each combination of `variable1`, `variable2`, and `qualifier` appears exactly once if duplicates are omitted across the date range. How does this differ from what you are trying to do?

**Comment by stutti49** [comment]
I am trying to export my database in a .csv file using "event list".
In my database, sometimes an organization Y (actors not specified) makes a statement several times. I would like that after the exportation in .csv file, the statement made by this organization Y appears only one time for this organization Y. But if an ACTOR makes the same statement on behalf of the SAME organization Y I would like to have it also in my .csv file. 

Currently when I export my database in .csv file and I select "ignore across date range" every statements which is made more than one time by the same actors do not appear at all in my file.

Maybe I have to specify my variable1, variable2, and qualifier more appropriately? but How in case of "event list"?

**Comment by leifeld** [comment]
I assume by "actors" you mean "persons"? In that case, have you tried setting "actors" as `variable 1` and "concepts" as `variable 2`? If I remember correctly, the function for ignoring duplicates takes these fields into account.

**Comment by stutti49** [comment]
Yes I meant person. Thank you for your quick and helpful help. It worked!!

**Comment by leifeld** [comment]
Great! Good luck with your analyses.
